//! `local/host-api-matches-types`: the host API and its published TypeScript definitions
//! disagreeing.
//!
//! §3: "The definitions are asserted against this crate's own registration [...] in both
//! directions. A definition that drifts from the engine is worse than none — it produces
//! confident autocomplete for a method that throws at run time." The reverse is quieter and
//! still costly: a host function nobody declares works and is invisible to anyone writing a
//! rule.
//!
//! This replaces two tests that scanned `host.rs` for the substring `object.set("` and split
//! the file on `#[cfg(test)]` to skip fixtures. The registration half is now matched on the
//! AST and skips test code structurally.
//!
//! The definitions half is still a text scan, and honestly so: a rule's query compiles once per
//! language it declares, so no single query matches both Rust call expressions and TypeScript
//! interface members, and §4 gives a rule access only to its own facts — which rules out
//! splitting the work across two rules that meet in a reduce phase. The fragile half moved
//! from the test into the rule; it did not disappear.
//!
//! `packages/lanekeep/index.d.ts` is read through `ctx.read_file`, so it is recorded as a cache
//! dependency and editing either file invalidates this entry.
//!
//! # A port, held to reporting identically
//!
//! This is `lanekeep/rules/host-api-matches-types.ts`, which was a TypeScript module until it
//! was this. The original was deleted in the commit that made this the shipped rule;
//! `git log --diff-filter=D -- lanekeep/rules/host-api-matches-types.ts` finds it. The two ran
//! against one shared table of cases in `crates/lanekeep-rules/tests/host_api_matches_types.rs`
//! until then, and the claim that table exists to hold is that they report the same violations
//! at the same positions with the same messages.
//!
//! **That claim outlives the file it was written against.** A difference here is a bug even when
//! it reads like an improvement, because the users being kept faith with are the ones whose
//! configs did not change: `Options` below does not reject an unknown key, for instance, because
//! the TypeScript rule ignored one and a stricter component would fail a run that used to pass.
//!
//! There are no unit tests in this crate, and that is a decision rather than an omission. It does
//! not compile at all without the `src/bindings.rs` that `cargo component build` generates, which
//! neither gate runs — so a `#[cfg(test)]` module here would be a test nobody executes, and one
//! of those is worse than none. Everything worth asserting is a case in that shared table
//! instead, where both implementations are held to it at once.
//!
//! # Nothing here may panic
//!
//! A panic in a guest is a trap, and a trap aborts the call before any report crosses back — so
//! a wrong assumption about a node's shape surfaces as "the host recorded no violations", which
//! is exactly what a broken `report` looks like too. Every lookup below is a `find` or a `get`
//! with an explicit fallback, and there is no indexing and no slicing anywhere in this file.

// The generated bindings. `warnings` covers the workspace's warn-level lints; `unsafe_code` is
// denied there and is not in the `warnings` group, and `wit-bindgen`'s output is unavoidably
// unsafe — it implements the canonical ABI. Scoped to this declaration and to the `export!`
// expansion at the bottom of the file rather than made a crate-level allow, so the rule's own
// code is still held to the workspace's `deny`.
#[allow(
    warnings,
    unsafe_code,
    reason = "`src/bindings.rs` is generated by `cargo component build` and implements the \
              canonical ABI, which cannot be written in safe Rust."
)]
mod bindings;

use std::cell::RefCell;
use std::collections::HashSet;

use bindings::lanekeep::host::types::{
    MatchEntry, RuleCard, RuleError, RuleExamples, RuleGates, RuleMetadata,
};
use bindings::{CheckContext, Guest, Match, ReduceContext};
// `Node` comes from the SDK rather than from the bindings, and there is nothing to reconcile:
// `wit-bindgen` resolves the world's `type node = u32` to a bare `u32` and emits no alias for
// it, so the SDK's own `pub type Node = u32` is the same type under a name the signatures below
// can be read against.
use lanekeep_rule::{Capture, Node, capture};
use serde::Deserialize;

/// The capture bound to the whole file, which is where every finding is reported.
const ROOT: &str = "root";

/// The capture bound to the method name of a `field_expression` in call position.
const METHOD: &str = "method";

/// The capture bound to the first string argument of a call.
const ARG: &str = "arg";

/// The capture bound to the whole call, which is where test-code exclusion is decided.
const CALL: &str = "call";

/// The method this rule is about: `object.set("name", ...)`.
const SET: &str = "set";

/// Registered names that are not context members.
///
/// `loc` builds a `{ file, line, column }` object with its own nested `object.set` calls, so
/// `file` is one of that object's fields rather than anything an author reaches directly.
/// `loc` itself is a real, declared context member and does not belong here — it was wrongly
/// listed until a review caught it, which is exactly the gap this exemption list exists to
/// avoid hiding: an exemption is only for a name that genuinely is not a context member, never
/// for one this rule found and nobody declared. Named individually rather than filtered by
/// heuristic, so a genuinely new host function cannot hide among them.
const NOT_CONTEXT_MEMBERS: [&str; 1] = ["file"];

/// The two interfaces whose members are the published context surface.
const INTERFACES: [&str; 2] = [
    "export interface RuleContext {",
    "export interface ReduceContext {",
];

thread_local! {
    /// The path of the host file this run reconciles, as configured.
    ///
    /// A component has no way to close over its options the way a JavaScript factory closes over
    /// them, so they arrive through `configure` and have to be put somewhere the later `check`
    /// calls can read. One instance is configured once and then checks many matches, which is
    /// why this is interior mutability rather than a value threaded through a call — the world
    /// gives `check` no parameter to thread it through.
    ///
    /// `RefCell` cannot be re-entered here: `configure` only writes and `check` only reads, and
    /// neither borrow outlives the closure it is taken in.
    static HOST_PATH: RefCell<String> = const { RefCell::new(String::new()) };
    /// The path of the types file, on the same terms as [`HOST_PATH`].
    static TYPES_PATH: RefCell<String> = const { RefCell::new(String::new()) };
}

/// This rule's options, as `configure` receives them.
///
/// `Option<String>` rather than `#[serde(default)] String`, so that an explicit `null` is the
/// default rather than a refusal — the TypeScript original spells this `options?.hostPath ?? …`,
/// which treats a null and a missing key alike, and a port that refused one of them would fail
/// a config the rule used to accept.
///
/// Unknown keys are accepted for the same reason. `deny_unknown_fields` would catch a typo,
/// which is a real benefit, and it is not taken here because the rule this replaces ignores one:
/// making the component stricter would turn a working config into a failed run at the moment the
/// rule is swapped over, which is not a change that belongs inside a migration.
#[derive(Debug, Default, Deserialize)]
struct Options {
    #[serde(rename = "hostPath")]
    host_path: Option<String>,
    #[serde(rename = "typesPath")]
    types_path: Option<String>,
}

/// A generated capture, seen through the SDK's projection.
///
/// One `impl` rather than a conversion at every `check`: `Capture` asserts a shape — "has a name
/// and a node" — over the type `wit-bindgen` generated in *this* crate, so there is no second
/// Rust copy of the WIT record to drift from it, and no orphan-rule problem either.
impl Capture for MatchEntry {
    fn name(&self) -> &str {
        &self.name
    }

    fn node(&self) -> Node {
        self.node
    }
}

struct HostApiMatchesTypes;

impl Rule for HostApiMatchesTypes {
    fn metadata() -> RuleMetadata {
        RuleMetadata {
            id: "local/host-api-matches-types".to_owned(),
            languages: vec!["rust".to_owned()],
            severity: "error".to_owned(),
            card: RuleCard {
                message: "the host API and its published types disagree".to_owned(),
                remediation: "register the function and declare it in the same change — and \
                              bump `host_api_version`, which is a cache key input"
                    .to_owned(),
                examples: RuleExamples {
                    bad: "object.set(\"newThing\", ...) with no entry in index.d.ts".to_owned(),
                    good: "both, together, with the version bumped".to_owned(),
                },
            },
            // One match per file: the whole reconciliation is a single invocation, because a
            // comparison of two sets cannot be made one call at a time.
            query: "(source_file) @root".to_owned(),
            // No gates, deliberately. The rule already returns early on any file that is not
            // the host file, and the types file is read through `ctx.read_file` — so a gate
            // would only duplicate the early return and could not narrow the read.
            gates: RuleGates {
                path_matches: Vec::new(),
                path_not_matches: Vec::new(),
                file_contains: Vec::new(),
                file_not_contains: Vec::new(),
            },
            timeout: None,
        }
    }

    fn configure(options_json: String) -> Result<(), String> {
        // `Option<Options>` rather than `Options`, because the world sends `null` for a rule
        // named with no options and serde will not deserialize a null into a struct. One code
        // path either way, which is what the world's `null` is for.
        let options: Option<Options> = serde_json::from_str(&options_json)
            .map_err(|e| format!("local/host-api-matches-types could not read its options: {e}"))?;
        let options = options.unwrap_or_default();
        let host_path = options
            .host_path
            .unwrap_or_else(|| "crates/lanekeep-js/src/host.rs".to_owned());
        let types_path = options
            .types_path
            .unwrap_or_else(|| "packages/lanekeep/index.d.ts".to_owned());
        HOST_PATH.with_borrow_mut(|configured| *configured = host_path);
        TYPES_PATH.with_borrow_mut(|configured| *configured = types_path);
        Ok(())
    }

    fn has_check() -> bool {
        true
    }

    /// No cross-file pass. Every export is mandatory because a WIT world has no optional ones.
    fn has_reduce() -> bool {
        false
    }

    fn check(ctx: &CheckContext, m: Match) -> Result<(), RuleError> {
        let Some(root) = capture(&m, ROOT) else {
            // The query below binds `root` on every match, so this is unreachable — and it is a
            // `return` rather than an assertion because the alternative in a guest is a trap,
            // which the host cannot tell apart from a rule that found nothing.
            return Ok(());
        };

        let host_path = HOST_PATH.with_borrow(String::clone);
        let types_path = TYPES_PATH.with_borrow(String::clone);

        // Only the host file is this rule's business; every other file is skipped before the
        // types file is read, so a run over a whole project reads it once.
        if ctx.file_path() != host_path {
            return Ok(());
        }

        // A refusal throws in the TypeScript original and an absence returns `undefined`; the
        // WIT `read_file` keeps that distinction as `Err` versus `Ok(None)`. The `Err` arm
        // fails the run the way the throw did, and the `None` arm reports the missing-types
        // message the original reports.
        let types = match ctx.read_file(&types_path) {
            Ok(Some(text)) => text,
            Ok(None) => {
                ctx.report(
                    root,
                    Some(&format!(
                        "`{types_path}` is missing, so the host API has no published types to \
                         agree with"
                    )),
                    None,
                );
                return Ok(());
            }
            Err(e) => {
                return Err(RuleError {
                    message: format!("could not read `{types_path}`: {e}"),
                    frames: Vec::new(),
                });
            }
        };

        let registered = registered_names(ctx, root);
        let declared = declared_members(&types);

        // A declared method that throws at run time is worse than no types.
        let mut declared_sorted: Vec<&String> = declared.iter().collect();
        declared_sorted.sort();
        for name in declared_sorted {
            if registered.contains(name) {
                continue;
            }
            ctx.report(
                root,
                Some(&format!(
                    "index.d.ts declares `{name}`, which host.rs does not register — \
                     autocomplete for a method that throws"
                )),
                None,
            );
        }

        // A host function nobody can find is as good as absent.
        let mut registered_sorted: Vec<&String> = registered.iter().collect();
        registered_sorted.sort();
        for name in registered_sorted {
            if declared.contains(name) {
                continue;
            }
            if NOT_CONTEXT_MEMBERS.contains(&name.as_str()) {
                continue;
            }
            ctx.report(
                root,
                Some(&format!(
                    "host.rs registers `{name}`, which packages/lanekeep/index.d.ts does not \
                     declare — it works but nobody can find it"
                )),
                None,
            );
        }

        Ok(())
    }

    /// Nothing. This rule has no cross-file pass; see [`HostApiMatchesTypes::has_reduce`].
    fn reduce(_ctx: &ReduceContext) -> Result<(), RuleError> {
        Ok(())
    }
}

/// The names `host.rs` registers, as a set.
///
/// Matched on the AST rather than by scanning for the substring `object.set("`, so a line break
/// inside the call cannot defeat it and test code is excluded structurally.
fn registered_names(ctx: &CheckContext, root: Node) -> HashSet<String> {
    let query = "(call_expression function: (field_expression field: (field_identifier) @method) \
                 arguments: (arguments . (string_literal) @arg)) @call";
    // The query is a compile-time constant, so the compiler cannot reject it; an error here is
    // unreachable, and an empty list is the safe direction for a rule that would otherwise trap.
    let matches = ctx.query_subtree(root, query).unwrap_or_default();

    let mut registered = HashSet::new();
    for hit in matches {
        let (Some(method), Some(arg), Some(call)) = (
            capture(&hit, METHOD),
            capture(&hit, ARG),
            capture(&hit, CALL),
        ) else {
            continue;
        };
        if ctx.text(method).as_deref() != Some(SET) {
            continue;
        }
        if in_test_code(ctx, call) {
            continue;
        }
        let arg = ctx.text(arg).unwrap_or_default();
        registered.insert(strip_quotes(&arg).to_owned());
    }
    registered
}

/// Members declared on the two context interfaces: a line reading `name(`, `name:` or `name?(`.
///
/// A text scan rather than a query, for the reason the crate documentation gives: no single
/// query matches both Rust call expressions and TypeScript interface members.
fn declared_members(types: &str) -> HashSet<String> {
    let mut names = HashSet::new();

    for header in INTERFACES {
        let Some(start) = types.find(header) else {
            continue;
        };
        let body = &types[start + header.len()..];
        let end = body.find("\n}").unwrap_or(body.len());

        for raw in body[..end].split('\n') {
            let mut line = raw.trim();
            if line.is_empty()
                || line.starts_with("//")
                || line.starts_with('*')
                || line.starts_with("/*")
            {
                continue;
            }
            if let Some(stripped) = line.strip_prefix("readonly ") {
                line = stripped;
            }

            // `^[A-Za-z0-9_]+`: the leading run of identifier characters. All ASCII, so the
            // char count is a byte count and the slice below cannot land on a boundary.
            let name_len = line
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                .count();
            if name_len == 0 {
                continue;
            }
            let name = &line[..name_len];
            let after = &line[name_len..];
            if after.starts_with('(') || after.starts_with(':') || after.starts_with("?(") {
                names.insert(name.to_owned());
            }
        }
    }

    names
}

/// Strip a Rust string literal's quotes and raw-string prefix, porting the TypeScript
/// `.replace(/^r?#*"/, '').replace(/"#*$/, '')`.
///
/// A Rust string literal carries its quotes, and a raw string carries `r` and any number of
/// `#`. Stripping a leading `r` unconditionally would eat the first letter of `readFile`,
/// `report` and `root` — so the `r` is only stripped when it is followed by `#*"`, which is
/// exactly what a raw-string prefix looks like.
fn strip_quotes(text: &str) -> &str {
    let mut rest = text;

    // Leading `r?#*"`: an optional `r`, then any `#`, then the opening `"`.
    if let Some(after_r) = rest.strip_prefix('r') {
        rest = after_r;
    }
    let leading_hashes = rest.bytes().take_while(|&b| b == b'#').count();
    rest = &rest[leading_hashes..];
    if let Some(after_quote) = rest.strip_prefix('"') {
        rest = after_quote;
    }

    // Trailing `"#*`: the closing `"`, then any `#` after it. The TypeScript regex `/"#*$/`
    // matches a `"` followed by `#*` at the end, so the last `"` is found and stripped along
    // with whatever `#`s follow it — not the `#`s that precede it. Only when everything after
    // the last `"` is `#`s, so a name that merely ends in `#` is not eaten.
    if let Some(quote) = rest.rfind('"')
        && rest[quote + 1..].bytes().all(|b| b == b'#')
    {
        rest = &rest[..quote];
    }

    rest
}

/// Whether this node sits inside `#[test]` or `#[cfg(test)]`.
///
/// Walked upwards rather than matched in the query, because the attribute is a *sibling* of the
/// item it applies to rather than a child — a query anchored on the attribute could not also
/// capture the call inside the function it decorates.
fn in_test_code(ctx: &CheckContext, node: Node) -> bool {
    let chain = ctx.ancestors(node);

    for (index, &ancestor) in chain.iter().enumerate() {
        let kind = ctx.kind(ancestor).unwrap_or_default();
        if kind != "function_item" && kind != "mod_item" {
            continue;
        }

        // The next entry in the chain, rather than `ctx.parent(ancestor)`.
        //
        // In TypeScript that mattered because a node crosses as an integer handle and the root's
        // is `0`, so `if (!parent)` discarded the root and no top-level `#[test]` was ever found.
        // Rust's `parent` returns `Option<Node>` and `Some(0)` is a perfectly good root, so the
        // bug is not expressible here — but `unwrap_or(0)` would put it back, and reading the
        // chain sidesteps the question the way the original does.
        let Some(&parent) = chain.get(index + 1) else {
            continue;
        };

        // Held once rather than asked per sibling. `None` is not reachable for a live handle,
        // and treating it as "no position" is the safe direction: comparing two absent positions
        // as equal would make the first sibling look like the item.
        let (Some(line), Some(column)) = (ctx.line(ancestor), ctx.column(ancestor)) else {
            continue;
        };

        // Attributes are *preceding siblings*, so walk the parent's children and keep the run of
        // `attribute_item`s immediately before this item. Reading the item's own children finds
        // nothing — which is a rule that silently never exempts anything.
        let mut attached: Vec<String> = Vec::new();
        for sibling in ctx.named_children(parent) {
            if ctx.kind(sibling).as_deref() == Some("attribute_item") {
                attached.push(ctx.text(sibling).unwrap_or_default());
                continue;
            }
            if ctx.line(sibling) == Some(line) && ctx.column(sibling) == Some(column) {
                if attached.iter().any(|a| mentions_test(a)) {
                    return true;
                }
                break;
            }
            // Any other item ends the run: those attributes belonged to it, not to us.
            attached.clear();
        }
    }
    false
}

/// Whether an attribute's text contains `test` as a whole word.
///
/// The TypeScript original writes this as `/\btest\b/`, so this is that regular expression and
/// not a looser reading of it: `#[test]`, `#[cfg(test)]` and `#[tokio::test]` match, while
/// `#[testing]` and `#[my_test]` do not — JavaScript's `\w` is `[A-Za-z0-9_]`, so an underscore
/// is a word character on both sides and `my_test` has no boundary before its `test`.
///
/// Non-overlapping search is exact here rather than approximate: a second `test` starting inside
/// a first would have a word character immediately before it, so it could not have matched
/// anyway.
fn mentions_test(text: &str) -> bool {
    let bytes = text.as_bytes();
    text.match_indices("test").any(|(start, needle)| {
        let before = start.checked_sub(1).and_then(|index| bytes.get(index));
        let after = bytes.get(start + needle.len());
        before.is_none_or(|b| !is_word_byte(*b)) && after.is_none_or(|b| !is_word_byte(*b))
    })
}

/// Whether a byte is one JavaScript's `\w` matches. ASCII only, as `\w` is.
fn is_word_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || byte == b'_'
}

// The rules this component hosts, and the dispatch the world's rule index drives.
//
// One rule, so this component is a ruleset of one and answers to index zero. The macro is what
// keeps that true without this file spelling a number: `rules` reports the list and every other
// export looks its index back up in the same list, so an id and a type cannot drift apart.
//
// A plain comment rather than `///`: a doc comment on a macro invocation documents nothing, and
// `unused_doc_comments` is an error under this workspace's lints.
lanekeep_rule::ruleset! {
    "local/host-api-matches-types" => HostApiMatchesTypes,
}

/// The canonical-ABI shims that make the seven exports reachable from the host.
///
/// In a module of its own so the `unsafe_code` the expansion needs is allowed *here* and not
/// across the rule's own code, which the workspace still denies it in. The macro takes bare
/// identifiers rather than paths, which is why the two it names are imported rather than
/// spelled out.
///
/// `warnings` alongside `unsafe_code`, on the same terms as `mod bindings` above: the expansion
/// calls `bindings`' own underscore-prefixed shims, which is seven `clippy::used_underscore_items`
/// under this workspace's `pedantic`. The `engine-rule` fixture this crate is modeled on has no
/// `[lints]` table of its own, so the template never had to answer for the expansion's lints and
/// dropping `warnings` here looks harmless right up until `cargo clippy` runs.
#[allow(
    warnings,
    unsafe_code,
    reason = "The expansion implements the canonical ABI, which cannot be written in safe Rust, \
              and reaches into the generated bindings' internal shims to do it."
)]
mod export {
    use super::{Component, bindings};

    bindings::export!(Component with_types_in bindings);
}
