[package]
name = "lanekeep-lang-go"
description = "Go language support for lanekeep."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
lanekeep-lang = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-go = { workspace = true }

[lints]
workspace = true
