# lanekeep task definitions.
#
# This file is the single source of truth for what every check means. Git hooks and
# CI both invoke these recipes rather than spelling out their own commands, so local
# and CI cannot drift: if `just check` passes on your machine, it passes in CI, and
# a change to a check happens in exactly one place.

set shell := ["bash", "-euo", "pipefail", "-c"]
set dotenv-load := false

# Show available recipes.
default:
    @just --list --unsorted

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------

# Install development tooling and activate the committed git hooks.
setup:
    @./scripts/setup-dev.sh

# Fail with an actionable message when a required tool is missing.
_require tool:
    #!/usr/bin/env bash
    set -euo pipefail
    if ! command -v {{ tool }} >/dev/null 2>&1; then
        echo "error: '{{ tool }}' is not installed." >&2
        echo "       run 'just setup' to install the full development toolchain." >&2
        exit 1
    fi

# ---------------------------------------------------------------------------
# The two gates. Everything else is a component of one of them.
# ---------------------------------------------------------------------------

# Pre-commit gate. Fast enough to run on every commit without being resented.
check-fast: fmt-check lint test test-rust-rules test-scripts test-go test-js

# Full gate. What CI runs and what pre-push runs. If this is green, the PR is green.
check: fmt-check lint test test-rust-rules test-scripts test-go test-js docs deny machete typos-check msrv

# ---------------------------------------------------------------------------
# Components
# ---------------------------------------------------------------------------

# Apply formatting.
fmt: (_fmt-rust-rules)
    cargo fmt --all

# Verify formatting without changing anything.
fmt-check: (_fmt-rust-rules "--check")
    cargo fmt --all -- --check

# rust-rules/ is a second workspace, and `cargo fmt` cannot be pointed at it.
#
# Two obstacles, and each rules out the obvious command. `cargo fmt --all
# --manifest-path rust-rules/Cargo.toml` follows `mod bindings;` into `src/bindings.rs` —
# generated by `cargo component build`, gitignored, and reformatted by rustfmt into
# something the next build overwrites — so it reports diffs in a file nobody edits. And
# dropping `--all` does not help: on a fresh checkout that generated file does not exist at
# all, and rustfmt fails with `failed to resolve mod`, which would make both gates depend on
# `cargo component` when they deliberately do not.
#
# So rustfmt is invoked directly, on a file list git produces, with `skip_children=true`.
#
# **`skip_children` is a nightly-only option, and this line works only because `--config`
# does not enforce that.** Put the same setting in a `rustfmt.toml` on stable and rustfmt
# warns — `can't set skip_children = true, unstable features are only available in nightly
# channel` — and ignores it; passed as `--config` it applies, silently. So consolidating this
# flag into a `rust-rules/rustfmt.toml`, which reads like tidying, is a silent no-op that
# makes `just fmt` start rewriting the generated file. It stays on the command line, and
# `AGENTS.md` carries the measurement.
#
# The file list comes from `git ls-files` rather than from `find`, so the exclusions are
# git's own: `target/` and `src/bindings.rs` are gitignored, which is the same fact
# `crates/lanekeep-wasm/tests/fixture_currency.rs` reads them for. `--others
# --exclude-standard` includes a file that has been written but not yet staged, so `just fmt`
# formats a new rule the first time it is run rather than the first time it is added.
#
# Every file is passed by name, so `skip_children` skips nothing that is not in the list: a
# submodule added later is formatted because git lists it, not because rustfmt walked into it.
_fmt-rust-rules *ARGS:
    #!/usr/bin/env bash
    set -euo pipefail
    edition="$(grep -m1 '^edition' rust-rules/Cargo.toml | sed -E 's/.*"(.*)".*/\1/')"

    # NUL-separated into a file rather than into a bash array: macOS ships bash 3.2, where
    # `${#array[@]}` on an empty array is an unbound-variable error under `set -u`.
    list="$(mktemp)"
    trap 'rm -f "${list}"' EXIT

    # `--cached` lists what the index holds, which mid-refactor includes a file deleted from
    # the working tree but not yet staged as deleted — and rustfmt errors on a path that is
    # not there. Filtered here rather than left to fail, because that failure names the
    # formatter and the cause is the rename you are halfway through.
    #
    # An `if` rather than `[ -f ... ] && printf`: under `set -e` the `&&` list is the last
    # command in the loop body, so a missing file would exit the loop with a status nobody
    # asked for.
    git ls-files --cached --others --exclude-standard -z -- 'rust-rules/*.rs' \
        | while IFS= read -r -d '' file; do
              if [ -f "${file}" ]; then printf '%s\0' "${file}"; fi
          done > "${list}"

    # A file list that came back empty would format nothing and report success, which is the
    # one way this recipe could pass while checking no rule source at all.
    count="$(tr -cd '\0' < "${list}" | wc -c | tr -d ' ')"
    if [ "${count}" -eq 0 ]; then
        echo "error: git lists no Rust sources under rust-rules/." >&2
        echo "       nothing was formatted, so nothing was checked." >&2
        exit 1
    fi

    xargs -0 rustfmt --edition "${edition}" --config skip_children=true {{ ARGS }} < "${list}"

# Clippy across every target, warnings are errors.
#
# The second invocation reaches rust-rules/, which is its own workspace and so outside the
# first. No `--workspace` there, and it is the same trade `test-rust-rules` documents: a rule
# crate does not compile without the `src/bindings.rs` that `cargo component build` generates,
# so `--workspace` would put a tool neither gate requires on the critical path. What that
# leaves uncovered is the two rule crates' own source, which `_fmt-rust-rules` does check and
# which `crates/lanekeep-rules/tests/` exercises through the committed component.
lint:
    cargo clippy --workspace --all-targets --all-features -- -D warnings
    cargo clippy --manifest-path rust-rules/Cargo.toml --all-targets --all-features -- -D warnings

# Run the Rust test suite.
#
# `--no-tests=warn` rather than the default `fail`: the crate skeletons exist ahead of
# their milestones and legitimately contain no tests yet, but a silent pass would hide
# a genuinely empty suite. Warning keeps that visible. Tighten to `fail` when M0 lands
# and every crate has behavior to assert.
test *ARGS:
    @just _require cargo-nextest
    cargo nextest run --workspace --all-features --no-tests=warn {{ ARGS }}

# Doctests, which nextest does not run.
test-doc:
    cargo test --workspace --doc

# Build one WebAssembly component from a JavaScript or TypeScript entry module.
#
# Shared by `wasm-fixtures` and `typescript-builtins`, which are the only two recipes that
# produce a component this way and which must not differ in a single flag: the JavaScript
# fixture exists to establish what a rule can still reach once `componentize-js` has put it
# inside StarlingMonkey, and a fixture built differently from the thing it stands in for
# establishes nothing. Both are outside every gate, and both rewrite a committed artifact.
#
# **`--disable all` is load-bearing and is not tidiness.** Measured on the built-ins entry,
# 2026-08-10, jco 1.27.0: without it the artifact imports **eighteen** WASI interfaces beside
# the host one — `wasi:filesystem/{types,preopens}`, `wasi:clocks/{wall-clock,monotonic-clock}`,
# `wasi:random/random`, `wasi:http/{types,outgoing-handler}`, `wasi:io/{error,poll,streams}` and
# eight of `wasi:cli` — which is a filesystem, a clock, randomness, network and stdio in a
# component whose whole purpose is to have none of them. `crates/lanekeep-wasm/src/load.rs`
# refuses such an artifact at load, naming all eighteen. The flag costs 42,584 bytes
# (13,070,681 without against 13,028,097 with) — to a few dozen bytes, since neither side is
# reproducible — so the capabilities are nearly free to carry and would be very expensive to
# have.
#
# **A missing Node is an error here and not a skip**, unlike in `test-js`. Both of this
# recipe's callers end by recording digests of every source they were built from, and a build
# that was skipped would have its sources recorded against a binary nobody rebuilt — turning
# "a determined hand can bless without building" into the ordinary result of running the
# recipe, which is the one thing `crates/lanekeep-wasm/tests/fixture_currency.rs` says must
# never happen. Nothing in any gate needs Node: every artifact is committed and read with
# `include_bytes!`.
#
# **And unlike every component built from Rust, these are not byte-reproducible.** Measured
# 2026-08-10 with jco 1.27.0: three builds from an unchanged tree gave 13,023,574 / 13,023,571
# / 13,023,630 bytes and three distinct sha256s, differing in 2,968,012 bytes. The `wizer`
# snapshot is a heap image and SpiderMonkey's layout of it is not stable between processes. So
# `git status` is dirty after every run of either caller, and `AGENTS.md`'s "rebuild and see
# that nothing moved" check does not reach these two artifacts — restore one with
# `git checkout` when its digest is the only line that moved.
#
# `{{ ARGS }}` is unquoted on purpose, so that `--bundle-config <path>` arrives as two words.
# Every value is written in this file; none comes from a caller outside it.
_componentize source out *ARGS:
    #!/usr/bin/env bash
    set -euo pipefail
    just _require node
    just _require npx
    echo "componentizing {{ source }}"
    npx --prefix packages/lanekeep jco componentize "{{ source }}" \
        --wit crates/lanekeep-wasm/wit --world-name rule --disable all --bundle \
        {{ ARGS }} -o "{{ out }}"

# Rebuild the committed WebAssembly test fixtures from their sources.
#
# Deliberately not part of any gate. The built components are committed, so the gate does
# not need `cargo component` and CI does not install it; this is what you run after
# changing a fixture's WIT or source, and the resulting `.wasm` is reviewed like any other
# change.
#
# The last step records what everything was built from, and it is what keeps the trade
# above honest: without it, editing a fixture's source and not running this recipe leaves
# every test in `lanekeep-wasm` asserting against the previous binary, green and
# meaningless. See `crates/lanekeep-wasm/tests/fixture_currency.rs`.
#
# `--target wasm32-unknown-unknown` is a requirement, not a preference. `cargo component`
# defaults to `wasm32-wasip1`, whose components import a wall clock and a filesystem as
# soon as the guest touches anything in `std` — the two capabilities the sandbox exists to
# withhold. On this target the import list is exactly the declared world.
wasm-fixtures:
    #!/usr/bin/env bash
    set -euo pipefail
    just _require cargo-component
    root="$(pwd)"
    built=0
    for dir in crates/lanekeep-wasm/tests/fixtures/*/; do
        [ -f "${dir}Cargo.toml" ] || continue
        name="$(basename "${dir}")"
        echo "building ${name}"
        built=$((built + 1))
        (cd "${dir}" && cargo component build --release --target wasm32-unknown-unknown)
        # cargo names the artifact after the crate with hyphens turned into underscores,
        # and the directory keeps the hyphens. `spike` has neither, so this only starts
        # mattering with the second fixture — a `cp` of a path that never existed.
        cp "${dir}target/wasm32-unknown-unknown/release/${name//-/_}.wasm" \
           "${root}/crates/lanekeep-wasm/tests/fixtures/${name}.wasm"
    done

    # A glob that matches no package builds nothing and says so in no way at all — and the
    # step below would then record the artifacts already in the tree as current, which is the
    # one thing this recipe must never do quietly.
    if [ "${built}" -eq 0 ]; then
        echo "error: no fixture crates under crates/lanekeep-wasm/tests/fixtures/." >&2
        echo "       nothing was rebuilt, so nothing may be re-recorded." >&2
        exit 1
    fi

    # And exactly one artifact built for the target every line above exists to avoid.
    #
    # `tests/load.rs` asserts that the load-time import check rejects a wrongly-targeted
    # component, and a check like that is only worth as much as the artifact it is pointed
    # at. Built here rather than described, because `AGENTS.md` records that a guest small
    # enough to allocate nothing has zero imports on *both* targets — so the difference has
    # to be produced to be believed.
    #
    # It sits one directory deeper than its siblings so the loop above cannot pick it up and
    # build it for the right target, and so `tests/world_shape.rs`'s glob over
    # `tests/fixtures/*.wasm` — which asserts every artifact it finds imports nothing but the
    # host interface — does not find the one artifact that must fail that assertion.
    echo "building wasip1 (deliberately for wasm32-wasip1)"
    dir="crates/lanekeep-wasm/tests/fixtures/rejected/wasip1/"
    (cd "${dir}" && cargo component build --release --target wasm32-wasip1)
    cp "${dir}target/wasm32-wasip1/release/wasip1.wasm" \
       "${root}/crates/lanekeep-wasm/tests/fixtures/rejected/wasip1.wasm"

    # And the one fixture that is not a Rust crate: a JavaScript rule component, which is the
    # only way to test what a rule can still reach once `componentize-js` has put it inside
    # StarlingMonkey. `crates/lanekeep-wasm/tests/js_globals.rs` says what that is and why it
    # matters.
    #
    # **Its build belongs here rather than being left to whoever remembers**, because the step
    # below re-records every source under `tests/fixtures/` whether this recipe built the
    # artifact beside it or not. A JS fixture this recipe skipped would therefore have its
    # sources blessed against a binary nobody rebuilt — turning "a determined hand can bless
    # without building" into the ordinary result of running the recipe, which is the one thing
    # `fixture_currency.rs` says it must never do.
    #
    # Everything else about the build — the flags, why a missing Node is an error rather than a
    # skip, and why the result is not byte-reproducible — is in `_componentize`, which the
    # shipped built-ins component shares. That sharing is not tidiness either: this fixture
    # stands in for that component, and a fixture built with different flags stands in for
    # nothing.
    just _componentize \
        crates/lanekeep-wasm/tests/fixtures/js-globals/rule.js \
        crates/lanekeep-wasm/tests/fixtures/js-globals.wasm

    # Record what all of that was built from, so the gate can tell a stale artifact from a
    # current one without needing `cargo component` to find out.
    #
    # `cargo test` rather than `cargo nextest run`, and not because of the runner: nextest
    # runs each test in its own process with no way to say "this one writes a file", and the
    # point here is the side effect rather than the verdict. The same test asserts under
    # `just test` with the variable unset.
    echo "recording fixture digests"
    LANEKEEP_BLESS_WASM_FIXTURES=1 cargo test --quiet -p lanekeep-wasm \
        --test fixture_currency -- --exact every_committed_artifact_is_the_one_its_sources_build

# Rebuild the committed rule components from rust-rules/.
#
# Deliberately not part of any gate, exactly as `wasm-fixtures` is not: it needs
# `cargo component`, which CI does not install, and it rewrites committed artifacts. The
# artifacts under `crates/lanekeep-rules/components/` are what the gate reads, through
# `lanekeep_rules::component`, so a machine with neither `cargo component` nor a wasm target
# still runs every rule component against `crates/lanekeep-rules/tests/`.
#
# `--target wasm32-unknown-unknown` is a requirement, not a preference — the same one
# `wasm-fixtures` documents at length. `cargo component` defaults to `wasm32-wasip1`, whose
# components import a wall clock and two filesystem interfaces as soon as the guest touches
# anything in `std`, and a rule crate parsing JSON touches plenty. On this target the import
# list is exactly the declared world, which `lanekeep-wasm`'s loader checks at load.
rust-rules:
    #!/usr/bin/env bash
    set -euo pipefail
    just _require cargo-component
    root="$(pwd)"
    built=0
    for dir in rust-rules/*/; do
        [ -f "${dir}Cargo.toml" ] || continue
        # A crate declaring a component target is a rule; one that does not is the SDK the
        # rules depend on, which is a plain host-target library and has no artifact to build.
        #
        # Anchored, and with the brackets: the SDK's manifest explains in a comment that it
        # carries no `[package.metadata.component.target]`, and an unanchored match found that
        # sentence and tried to copy an artifact the SDK never builds.
        grep -qE '^\[package\.metadata\.component\.target\]' "${dir}Cargo.toml" || continue
        name="$(basename "${dir}")"
        echo "building ${name}"
        built=$((built + 1))
        (cd "${dir}" && cargo component build --release --target wasm32-unknown-unknown)
        # One workspace, so one target directory for all of them. cargo names the artifact
        # after the crate with hyphens turned into underscores; the directory keeps them.
        cp "${root}/rust-rules/target/wasm32-unknown-unknown/release/${name//-/_}.wasm" \
           "${root}/crates/lanekeep-rules/components/${name}.wasm"
    done

    # A glob that matches no package builds nothing and says so in no way at all, leaving the
    # artifacts already in the tree in place and this recipe reporting success.
    if [ "${built}" -eq 0 ]; then
        echo "error: no rule crates under rust-rules/." >&2
        echo "       nothing was rebuilt, so nothing was refreshed." >&2
        exit 1
    fi

    # Clippy and rustdoc over the *whole* second workspace, which is possible here and nowhere
    # else. `just lint` and `just docs` run over `default-members`, because a rule crate does not
    # compile without the `src/bindings.rs` that the loop above just generated and no gate may
    # require `cargo component` to produce one. This recipe has already produced them, so this is
    # the one place the rule crates' own source can be held to the workspace lints and to
    # docs.rs's link resolution.
    #
    # **Before the recording, and that is what makes it more than advice.** These artifacts only
    # reach a commit through this recipe, and the digest manifest is what forces the recipe to be
    # run: a changed rule source with no re-record is a red gate. So placing the checks ahead of
    # the recording puts them on the only path to a green tree — a contributor who ignores a
    # clippy failure here has no recorded digest either, and `just check` says so. Recording
    # first would make this pair skippable by ignoring one exit code.
    #
    # The cost is that a failure here leaves rebuilt artifacts copied and their digests stale,
    # so the next `just check` reports the currency failure as well. That is not extra work:
    # the fix for it is to run this recipe again, which is what fixing the clippy error leads
    # to anyway.
    echo "checking the rule crates, now that their bindings exist"
    cargo clippy --manifest-path rust-rules/Cargo.toml --workspace --all-targets --all-features -- -D warnings
    RUSTDOCFLAGS="-D warnings" cargo doc --manifest-path rust-rules/Cargo.toml --workspace --no-deps --all-features

    # Record what all of that was built from, so the gate can tell a stale component from a
    # current one without needing `cargo component` to find out. Exactly what `wasm-fixtures`
    # does, and for the same reason: without it, editing a rule's source and not running this
    # recipe leaves `crates/lanekeep-rules/tests/` holding the *previous* component to the
    # current expectations, green and meaningless.
    #
    # A manifest and a variable of its own rather than the fixtures'. Sharing one would mean
    # this recipe re-recording the fixtures it did not build and `wasm-fixtures` re-recording
    # the components it did not build, which is how a stale artifact gets blessed by someone
    # doing the right thing elsewhere. `--exact` keeps this to the one test.
    echo "recording rule component digests"
    LANEKEEP_BLESS_RULE_COMPONENTS=1 cargo test --quiet -p lanekeep-wasm \
        --test fixture_currency -- --exact every_committed_rule_component_is_the_one_its_sources_build

# Rebuild the committed TypeScript built-ins component.
#
# The third recipe that rewrites a committed artifact, and outside every gate for the reason the
# other two are: it needs a toolchain the gate deliberately does not — Node here, rather than
# `cargo component` — and the artifact it produces is committed and read with `include_bytes!`.
# `just check` passes on a machine with no Node at all.
#
# **One component for every TypeScript rule, and not one each.** Measured on this entry,
# 2026-08-10: hosting `no-default-export` alone gives 13,021,569 bytes and hosting all four
# gives 13,028,097 — **6,528 bytes for three more rules**, against a per-rule cost of 13 MiB if
# each got its own component. What is being paid for is a StarlingMonkey build, and the rules
# are rounding error on it. `crates/lanekeep-rules/typescript/entry.ts` is where they are
# listed, and the index a rule sits at there is what `lanekeep_rules` dispatches on.
#
# `--bundle-config` is what makes lanekeep's own resolution rules apply to a bundler that would
# otherwise resolve imports the way npm does — see `typescript/rolldown.config.mjs`, which wires
# `packages/lanekeep/runtime/resolve.js` into rolldown rather than restating it. Everything else
# about the build is in `_componentize`, which the JavaScript fixture shares.
#
# The last step records what the artifact was built from, and it is the whole of the staleness
# check rather than half of it: `componentize-js` is not byte-reproducible, so there is no
# rebuild-and-diff to fall back on. See `crates/lanekeep-wasm/tests/fixture_currency.rs`.
typescript-builtins:
    #!/usr/bin/env bash
    set -euo pipefail
    just _componentize \
        crates/lanekeep-rules/typescript/entry.ts \
        crates/lanekeep-rules/components/typescript-builtins.wasm \
        --bundle-config crates/lanekeep-rules/typescript/rolldown.config.mjs

    # `cargo test` rather than `cargo nextest run`, for the reason `wasm-fixtures` gives: what
    # is wanted here is the side effect and not the verdict, and nextest has no way to say
    # "this one writes a file". The same test asserts under `just test` with the variable unset.
    echo "recording TypeScript component digests"
    LANEKEEP_BLESS_TYPESCRIPT_BUILTINS=1 cargo test --quiet -p lanekeep-wasm \
        --test fixture_currency -- --exact every_committed_typescript_component_is_the_one_its_sources_build

# Test rust-rules/: its own workspace, so `cargo test --workspace` at the root does not reach
# it.
#
# Part of both gates, unlike `rust-rules` — that recipe is excluded because it needs
# `cargo component` and rewrites committed artifacts, neither of which is true here: this is
# a zero-dependency host-target test that runs in under a second, and leaving it opt-in would
# mean nothing here runs until someone remembers to ask for it by name. `deny`, `machete`,
# `fmt-check`, `lint`, `docs` and `msrv` reach this workspace too now, each in its own recipe;
# what none of them reaches without `cargo component` is covered here and in `rust-rules`.
#
# **No `--workspace`, and that is load-bearing.** A rule crate's `src/bindings.rs` is generated
# by `cargo component build` and gitignored, so on a fresh checkout it does not exist and the
# crate does not compile at all — for any target, host included. `--workspace` would therefore
# make this recipe, and both gates through it, depend on a tool the gates deliberately do not
# require. `default-members` in `rust-rules/Cargo.toml` names what is buildable without one;
# what that leaves out is covered by running the committed artifact through the real engine in
# `crates/lanekeep-rules/tests/`, which is a stronger check than a host-target unit test.
#
# Plain `cargo test` rather than `cargo nextest run`: the crates here are host-target unit
# tests over pure functions, with no wasm target and no fixture side effects to isolate a
# process per test for, and `cargo test` also runs doctests in the same pass that nextest
# would need a second invocation for.
test-rust-rules:
    cargo test --manifest-path rust-rules/Cargo.toml --all-features

# Tests for the repository's own shell tooling.
#
# lint-commit-msg.sh gates every commit and every pull request title, and the title is
# what release-plz reads to pick the next version. A false accept ships a wrong release;
# a false reject blocks everyone. It is not too small to test.
test-scripts:
    @./scripts/test-lint-commit-msg.sh
    @./scripts/test-build-npm-packages.sh
    @./scripts/test-build-release-archives.sh
    @./scripts/test-build-homebrew-formula.sh
    @./scripts/test-build-python-wheels.sh
    @./scripts/test-publish-npm.sh
    @./scripts/test-publish-crates.sh
    @./scripts/test-publish-pypi.sh
    @./scripts/test-shell-portability.sh
    @./scripts/test-workflows.sh
    @./scripts/test-release-config.sh

# The Go launcher: formatting, vet, and its own tests.
#
# Skipped where Go is absent rather than failing. It is one distribution lane, and making
# the Rust gate require a Go toolchain would cost every contributor for something most of
# them never touch — the same trade `test-shell-portability.sh` makes for bash 3.2. CI has
# Go on every runner, so it is a real check there.
test-go:
    #!/usr/bin/env bash
    set -euo pipefail
    if ! command -v go >/dev/null 2>&1; then
        echo "note: no go toolchain here, so the launcher tests are skipped (CI covers them)"
        exit 0
    fi
    unformatted="$(gofmt -l ./cmd)"
    if [ -n "${unformatted}" ]; then
        echo "error: not gofmt'd:" >&2
        echo "${unformatted}" >&2
        exit 1
    fi
    go vet ./...
    go test ./...

# The authoring package's JavaScript tests.
#
# `packages/lanekeep/runtime/resolve.js` enforces the module-resolution rules a second time —
# `crates/lanekeep-js/src/loader.rs` enforces them at run time inside the sandbox, and that one
# enforces them at build time for a rule compiled ahead of time into a component. Its tests are
# ported from that file's one for one and *are* the port's specification. Not running them
# leaves the whole port resting on `resolver_parity.rs`, which only compares refusal messages.
#
# Skipped where Node is absent rather than failing, on `test-go`'s terms and for its reasons:
# componentizing is a maintainer's job, and making the Rust gate need a JavaScript toolchain
# would cost every contributor for something most of them never touch. The `gate` job runs on
# a runner that has Node, so it is a real check there.
#
# A Node too old to have `node --test` is an error rather than a skip. Absence is somebody's
# machine; a version that cannot run the suite is a misconfiguration, and a gate that quietly
# checks nothing because of one is the failure this recipe exists to prevent.
#
# **The file list is a glob, and `node --test <directory>` is not an option.** Since Node 23 a
# directory argument is executed as a module rather than searched, and it fails in the quiet
# direction one level up: `node --test packages/lanekeep/` exits 0 reporting one passing test,
# having loaded `index.js`, which declares none.
#
# An empty expansion is refused for the reason `_fmt-rust-rules` refuses one, and the list is
# NUL-separated through a file rather than a bash array for the reason that recipe explains —
# macOS ships bash 3.2, where `${#array[@]}` on an empty array is an error under `set -u`.
test-js:
    #!/usr/bin/env bash
    set -euo pipefail
    if ! command -v node >/dev/null 2>&1; then
        echo "note: no node here, so the authoring package's tests are skipped (CI covers them)"
        exit 0
    fi

    # Truncated at the first whitespace, so a carriage return cannot reach the comparison.
    major="$(node --version | sed -E 's/^v([0-9][0-9]*).*/\1/')"
    major="${major%%[![:digit:]]*}"
    if [ -z "${major}" ] || [ "${major}" -lt 18 ]; then
        echo "error: node $(node --version) has no built-in test runner." >&2
        echo "       lanekeep's authoring package needs node 18 or newer." >&2
        exit 1
    fi

    list="$(mktemp)"
    output="$(mktemp)"
    trap 'rm -f "${list}" "${output}"' EXIT

    find packages/lanekeep/runtime -maxdepth 1 -name '*.test.js' -print0 > "${list}"
    count="$(tr -cd '\0' < "${list}" | wc -c | tr -d ' ')"
    if [ "${count}" -eq 0 ]; then
        echo "error: no test files under packages/lanekeep/runtime/." >&2
        echo "       nothing ran, so nothing was checked." >&2
        exit 1
    fi

    if ! xargs -0 node --test --test-reporter=tap < "${list}" > "${output}"; then
        cat "${output}"
        exit 1
    fi

    # A file declaring no tests is counted by node as one passing test, so a green run is not
    # by itself evidence that anything executed.
    ran="$(sed -n 's/^# tests \([0-9][0-9]*\).*/\1/p' "${output}" | tail -1)"
    if [ -z "${ran}" ] || [ "${ran}" -eq 0 ]; then
        cat "${output}"
        echo "error: node reported no tests from ${count} file(s)." >&2
        exit 1
    fi
    echo "${ran} passed, 0 failed"

# Build documentation the way docs.rs will, failing on broken intra-doc links.
#
# The second invocation reaches rust-rules/, scoped the way `lint`'s is and for the same
# reason — see there.
docs:
    RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps --all-features
    RUSTDOCFLAGS="-D warnings" cargo doc --manifest-path rust-rules/Cargo.toml --no-deps --all-features

# Supply-chain policy: advisories, licenses, banned crates, source provenance.
#
# **The second invocation is the sharper of the two.** rust-rules/ has its own `Cargo.lock`, so
# nothing in the root graph names `wit-bindgen-rt`, `no-unwrap`, `no-glob-import` or
# `lanekeep-rule` — and those crates compile to the components under
# `crates/lanekeep-rules/components/`, which are `include_bytes!`d straight into the shipped
# binary. Without this line, advisories, licenses and §13's network-crate ban do not apply to a
# dependency graph that ships inside the product. `rust-rules/Cargo.toml`'s own header justifies
# the one-workspace layout on exactly this basis: one invocation rather than a loop.
#
# `--config` back at the root file rather than a second `deny.toml` beside that manifest.
# cargo-deny resolves its configuration relative to the manifest, so the copy would be the
# default and would drift — two policies, one of which nobody remembers to update, is worse than
# no second check at all.
deny:
    @just _require cargo-deny
    cargo deny --all-features check
    cargo deny --all-features --manifest-path rust-rules/Cargo.toml --config deny.toml check

# Known vulnerabilities in the dependency graph.
audit:
    @just _require cargo-audit
    cargo audit --deny warnings

# Dependencies declared but never used.
machete:
    @just _require cargo-machete
    cargo machete --with-metadata

# Spelling, across code and prose.
typos-check:
    @just _require typos
    typos

# Fix the spelling mistakes that can be fixed automatically.
typos-fix:
    @just _require typos
    typos --write-changes

# Verify the crate still builds on the MSRV declared in Cargo.toml.
#
# Part of `just check`, and it has to be. The pinned toolchain is far newer than the MSRV,
# so every other recipe happily accepts syntax that does not exist on the floor we promise —
# let-chains being the one that caught us out. Without this in the gate, "it passes locally"
# is false for exactly the failures hardest to guess at.
msrv:
    #!/usr/bin/env bash
    set -euo pipefail
    version=$(grep -m1 '^rust-version' Cargo.toml | sed -E 's/.*"(.*)".*/\1/')
    echo "checking against declared MSRV ${version}"
    rustup toolchain install "${version}" --profile minimal --no-self-update
    cargo "+${version}" check --workspace --all-features --all-targets

    # rust-rules/ declares its own floor, so it is read rather than assumed equal. It is a
    # separate promise about a separate workspace, and the two being the same number today is
    # not a reason for one grep to answer for both.
    #
    # Scoped the way `lint` and `docs` are: default members only, because a rule crate needs a
    # generated `src/bindings.rs` that no gate may require `cargo component` to produce.
    rules_version=$(grep -m1 '^rust-version' rust-rules/Cargo.toml | sed -E 's/.*"(.*)".*/\1/')
    echo "checking rust-rules against declared MSRV ${rules_version}"
    rustup toolchain install "${rules_version}" --profile minimal --no-self-update
    cargo "+${rules_version}" check --manifest-path rust-rules/Cargo.toml --all-features --all-targets

# ---------------------------------------------------------------------------
# Benchmarks and snapshots
# ---------------------------------------------------------------------------

# Run the benchmark suite against the fixture corpus.
#
# Prints each scenario against its budget from docs/architecture.md §15, and fails only
# past 4x — see the bench's own documentation for why the gate is loose and the report is
# not.
bench *ARGS:
    cargo bench --workspace {{ ARGS }}

# Review pending insta snapshots interactively.
snapshot:
    @just _require cargo-insta
    cargo insta review

# Accept every pending snapshot. Read the diff first — this is how a wrong
# expectation becomes the committed expectation.
snapshot-accept:
    @just _require cargo-insta
    cargo insta accept

# ---------------------------------------------------------------------------
# Slower analyses. Nightly in CI rather than per-pull-request.
# ---------------------------------------------------------------------------

# Mutation testing: are the tests actually asserting anything?
#
# The root workspace only, and rust-rules/ is left out on evidence rather than by oversight.
# cargo-mutants tests each mutant in a copy of the workspace root, and a rule crate names the
# engine's world through `../../crates/lanekeep-wasm/wit` — which resolves to nothing in that
# copy, so the component cannot be rebuilt and the expectations that would judge the mutant live
# in the other workspace anyway. `AGENTS.md` has the measurement, including why the scoped
# invocation's wall of MISSED results is an artifact of the wrong workspace and not a finding.
mutants *ARGS:
    @just _require cargo-mutants
    cargo mutants --workspace {{ ARGS }}

# Fuzz a target for a bounded time. `just fuzz config 60`
fuzz target seconds="60":
    @just _require cargo-fuzz
    cargo fuzz run {{ target }} -- -max_total_time={{ seconds }}

# ---------------------------------------------------------------------------
# Housekeeping
# ---------------------------------------------------------------------------

# Remove build output and lanekeep's own cache.
clean:
    cargo clean
    rm -rf .lanekeep

# Validate a commit message against Conventional Commits. Used by the commit-msg hook.
lint-commit-msg file:
    @./scripts/lint-commit-msg.sh {{ file }}
