// Code generated by wit-bindgen-go. DO NOT EDIT.

package types

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// OptionMatchShape is used for storage in variant or result types.
type OptionMatchShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Option[Match]{})]byte
}

// ReadErrorShape is used for storage in variant or result types.
type ReadErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(ReadError{})]byte
}

// OptionStringShape is used for storage in variant or result types.
type OptionStringShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Option[string]{})]byte
}

func lower_OptionString(v cm.Option[string]) (f0 uint32, f1 *uint8, f2 uint32) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1, v2 := cm.LowerString(*some)
		f1 = (*uint8)(v1)
		f2 = (uint32)(v2)
	}
	return
}

func lower_OptionBool(v cm.Option[bool]) (f0 uint32, f1 uint32) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1 := (uint32)(cm.BoolToU32(*some))
		f1 = (uint32)(v1)
	}
	return
}

func lower_Fix(v Fix) (f0 uint32, f1 *uint8, f2 uint32, f3 uint32, f4 uint32) {
	f0 = (uint32)(v.Node)
	f1, f2 = cm.LowerString(v.Text)
	f3, f4 = lower_OptionBool(v.Safe)
	return
}

func lower_OptionFix(v cm.Option[Fix]) (f0 uint32, f1 uint32, f2 *uint8, f3 uint32, f4 uint32, f5 uint32) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1, v2, v3, v4, v5 := lower_Fix(*some)
		f1 = (uint32)(v1)
		f2 = (*uint8)(v2)
		f3 = (uint32)(v3)
		f4 = (uint32)(v4)
		f5 = (uint32)(v5)
	}
	return
}

func lower_OptionU32(v cm.Option[uint32]) (f0 uint32, f1 uint32) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1 := (uint32)(*some)
		f1 = (uint32)(v1)
	}
	return
}

func lower_ReduceLocation(v ReduceLocation) (f0 *uint8, f1 uint32, f2 uint32, f3 uint32, f4 uint32, f5 uint32) {
	f0, f1 = cm.LowerString(v.File)
	f2, f3 = lower_OptionU32(v.Line)
	f4, f5 = lower_OptionU32(v.Column)
	return
}
