// Code generated by wit-bindgen-go. DO NOT EDIT.

package types

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "lanekeep:host@0.1.0".

//go:wasmimport lanekeep:host/types@0.1.0 [resource-drop]check-context
//go:noescape
func wasmimport_CheckContextResourceDrop(self0 uint32)

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.ancestors
//go:noescape
func wasmimport_CheckContextAncestors(self0 uint32, n0 uint32, result *cm.List[Node])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.binding-kind
//go:noescape
func wasmimport_CheckContextBindingKind(self0 uint32, n0 uint32, result *cm.Option[BindingKind])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.children
//go:noescape
func wasmimport_CheckContextChildren(self0 uint32, n0 uint32, result *cm.List[Node])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.closest-ancestor
//go:noescape
func wasmimport_CheckContextClosestAncestor(self0 uint32, n0 uint32, query0 *uint8, query1 uint32, result *cm.Result[OptionMatchShape, cm.Option[Match], string])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.column
//go:noescape
func wasmimport_CheckContextColumn(self0 uint32, n0 uint32, result *cm.Option[uint32])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.emit-fact
//go:noescape
func wasmimport_CheckContextEmitFact(self0 uint32, kind0 *uint8, kind1 uint32, data0 *uint8, data1 uint32, result *cm.Result[FactError, struct{}, FactError])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.file-exists
//go:noescape
func wasmimport_CheckContextFileExists(self0 uint32, path0 *uint8, path1 uint32, result *cm.Result[ReadErrorShape, bool, ReadError])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.file-path
//go:noescape
func wasmimport_CheckContextFilePath(self0 uint32, result *string)

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.file-text
//go:noescape
func wasmimport_CheckContextFileText(self0 uint32, result *string)

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.is-imported-from
//go:noescape
func wasmimport_CheckContextIsImportedFrom(self0 uint32, n0 uint32, pattern0 *uint8, pattern1 uint32) (result0 uint32)

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.is-named
//go:noescape
func wasmimport_CheckContextIsNamed(self0 uint32, n0 uint32) (result0 uint32)

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.is-shadowed
//go:noescape
func wasmimport_CheckContextIsShadowed(self0 uint32, n0 uint32) (result0 uint32)

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.kind
//go:noescape
func wasmimport_CheckContextKind(self0 uint32, n0 uint32, result *cm.Option[string])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.line
//go:noescape
func wasmimport_CheckContextLine(self0 uint32, n0 uint32, result *cm.Option[uint32])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.loc
//go:noescape
func wasmimport_CheckContextLoc(self0 uint32, n0 uint32, result *cm.Option[NodeLocation])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.named-children
//go:noescape
func wasmimport_CheckContextNamedChildren(self0 uint32, n0 uint32, result *cm.List[Node])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.parent
//go:noescape
func wasmimport_CheckContextParent(self0 uint32, n0 uint32, result *cm.Option[Node])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.query-subtree
//go:noescape
func wasmimport_CheckContextQuerySubtree(self0 uint32, n0 uint32, query0 *uint8, query1 uint32, result *cm.Result[cm.List[Match], cm.List[Match], string])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.read-file
//go:noescape
func wasmimport_CheckContextReadFile(self0 uint32, path0 *uint8, path1 uint32, result *cm.Result[OptionStringShape, cm.Option[string], ReadError])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.report
//go:noescape
func wasmimport_CheckContextReport(self0 uint32, n0 uint32, message0 uint32, message1 *uint8, message2 uint32, fix0 uint32, fix1 uint32, fix2 *uint8, fix3 uint32, fix4 uint32, fix5 uint32)

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.resolves-to-import
//go:noescape
func wasmimport_CheckContextResolvesToImport(self0 uint32, n0 uint32, module0 *uint8, module1 uint32, name0 uint32, name1 *uint8, name2 uint32) (result0 uint32)

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.root
//go:noescape
func wasmimport_CheckContextRoot(self0 uint32) (result0 uint32)

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.text
//go:noescape
func wasmimport_CheckContextText(self0 uint32, n0 uint32, result *cm.Option[string])

//go:wasmimport lanekeep:host/types@0.1.0 [method]check-context.today
//go:noescape
func wasmimport_CheckContextToday(self0 uint32, result *cm.Option[string])

//go:wasmimport lanekeep:host/types@0.1.0 [resource-drop]reduce-context
//go:noescape
func wasmimport_ReduceContextResourceDrop(self0 uint32)

//go:wasmimport lanekeep:host/types@0.1.0 [method]reduce-context.facts
//go:noescape
func wasmimport_ReduceContextFacts(self0 uint32, kind0 uint32, kind1 *uint8, kind2 uint32, result *cm.List[EmittedFact])

//go:wasmimport lanekeep:host/types@0.1.0 [method]reduce-context.files
//go:noescape
func wasmimport_ReduceContextFiles(self0 uint32, result *cm.List[string])

//go:wasmimport lanekeep:host/types@0.1.0 [method]reduce-context.report
//go:noescape
func wasmimport_ReduceContextReport(self0 uint32, at0 *uint8, at1 uint32, at2 uint32, at3 uint32, at4 uint32, at5 uint32, message0 uint32, message1 *uint8, message2 uint32)
