// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package types represents the imported interface "lanekeep:host/types@0.1.0".
//
// The whole host surface: the data types that cross the boundary, and the two contexts
// that carry the functions.
//
// One interface, not one per phase, and that was decided by building both.
//
// The alternative on the table was three interfaces — `types`, `check-api`, `reduce-api`
// —
// on the theory that a per-file rule could then not so much as *name* the cross-file
// context. Both variants were written out in full and the same guest built against
// each on
// 2026-08-05, `wasm-tools` 1.255.0, `cargo-component` 0.21.1, `wit-bindgen` 0.41.0,
// `rustc` 1.95.0, `wasm32-unknown-unknown`:
//
// | | artifact imports | bytes | guest bindings name both contexts |
// |---|---|---|---|
// | one interface | 1 | 26,644 | yes |
// | three interfaces | 3 | 26,979 | yes |
//
// **The split does not deliver what it was proposed for.** The `rule` world exports
// both
// `check` and `reduce`, so it must import both phases' interfaces to give those two
// exports their argument types; `wit-parser` then adds `import types` on its own,
// and the
// split guest's bindings open with `pub type CheckContext = ...` and
// `pub type ReduceContext = ...` exactly as the single-interface guest's do. Literal
// unnameability needs two *worlds*, which doubles the build artifact for every rule
// that
// has a reduce phase — and that trade was already rejected. So the split costs three
// imports where one will do, and buys nothing.
//
// The residual weakness is therefore real and is stated plainly rather than described
// as
// impossible: a per-file rule can name `reduce-context`, and the generated bindings
// hand
// it a `pub unsafe fn from_handle(handle: u32)` with which to forge one. What it
// cannot do
// is obtain a *valid* one. Two independent layers stop it. The method sets are disjoint,
// so a wrong-phase call does not compile. And a forged handle traps in the runtime
// with
// "unknown handle index", because the instance's table for the other phase's resource
// is
// empty during this call — the host is never reached, and it records that it was
// never
// reached. That second layer is the load-bearing one, since a compile error only
// guards a
// rule someone compiles from source and says nothing about a component that arrives
// prebuilt.
//
// **Both layers are now measured against this world rather than against the prototype,
// and
// in both directions.** `tests/fixtures/reduce/` forges the other phase's handle
// from each
// phase, with the bindings' own `unsafe fn from_handle(0)` — zero being the handle
// the call
// already holds for its own phase, which is the most plausible forgery available.
// Measured
// 2026-08-06, `wasmtime` 47.0.3, `cargo-component` 0.21.1, `rustc` 1.95.0: the trap's
// root
// cause is exactly `unknown handle index 0`, the other phase's host state records
// nothing,
// and the guest's own announcement immediately before the forgery *is* recorded —
// so the
// call died at the forgery and not earlier. The compile-time layer was confirmed
// by hand in
// the same fixture: `ctx.files()` inside `check` fails with “error[E0599]: no method
// named
// `files` found for reference `&types::CheckContext` in the current scope“. Both
// are
// described in `tests/reduce.rs`, which owns the runtime half; the declaration half
// — that
// the two blocks below share exactly one method name — is asserted against this file
// in
// `tests/facts.rs`.
package types

import (
	"go.bytecodealliance.org/cm"
)

// Node represents the u32 "lanekeep:host/types@0.1.0#node".
//
// An opaque reference into the arena of the check-context that produced it. Meaningless
// outside the call that handed it out — the same discipline the published `Node`
// type
// already enforces in TypeScript, restated in a form every target language shares.
//
// The root of a parsed file is handle 0. Compare against a sentinel explicitly, never
// test truthiness: `if (!node)` discards the root, silently, and only ever by removing
// results. This is why `closest-ancestor` returns `option<match>` rather than an
// empty
// list.
//
//	type node = u32
type Node uint32

// NodeLocation represents the record "lanekeep:host/types@0.1.0#node-location".
//
// Where a per-file violation is reported. Every field is known, because a `node`
// always
// has a position in the file it came from.
//
//	record node-location {
//		file: string,
//		line: u32,
//		column: u32,
//	}
type NodeLocation struct {
	_      cm.HostLayout `json:"-"`
	File   string        `json:"file"`
	Line   uint32        `json:"line"`
	Column uint32        `json:"column"`
}

// ReduceLocation represents the record "lanekeep:host/types@0.1.0#reduce-location".
//
// Where a cross-file violation is reported. The reduce phase never touches parse
// trees
// (`docs/architecture.md`'s reduce invariant), so it has no node to take a position
// from
// and must carry one captured earlier — on a fact, during the per-file pass, while
// the
// tree was still there.
//
// **`line` and `column` are optional in this record and required by the host.** The
// option
// mirrors the published TypeScript `ReduceLocation`, where both have always been
// optional
// in the type and required by the runtime; it is not permission to omit them. A `report`
// naming no site fails the call, in both engines, because the only stand-in available
// downstream is 1:1 — which points a reader at an unrelated line and cannot be told
// apart
// from a rule that meant 1:1. A rule that means "the whole file" says `1, 1` itself.
//
// Declaring them `u32` would make that structural rather than enforced, and is the
// stronger
// shape. It is not taken here because it would put this record out of step with the
// published type it mirrors, and because it is an ABI change. That second reason
// used to
// carry a window with it — cheap only while no authoring crate binds against this
// world —
// and the window has closed: `rust-rules/no-unwrap` and `rust-rules/no-glob-import`
// both
// point `[package.metadata.component.target]` at this directory, and their artifacts
// are
// committed and hashed. Changing the record now invalidates every one of them and
// any
// component built outside this repository besides, which inverts what this paragraph
// used
// to recommend: the option stays, and the host keeps enforcing what the type will
// not.
//
//	record reduce-location {
//		file: string,
//		line: option<u32>,
//		column: option<u32>,
//	}
type ReduceLocation struct {
	_      cm.HostLayout     `json:"-"`
	File   string            `json:"file"`
	Line   cm.Option[uint32] `json:"line"`
	Column cm.Option[uint32] `json:"column"`
}

// Fix represents the record "lanekeep:host/types@0.1.0#fix".
//
// A suggested edit replacing a node's text.
//
//	record fix {
//		node: node,
//		text: string,
//		safe: option<bool>,
//	}
type Fix struct {
	_    cm.HostLayout `json:"-"`
	Node Node          `json:"node"`
	Text string        `json:"text"`

	// The rule's own claim that applying this preserves behavior, which the engine does
	// not
	// verify. `--fix` applies the safe ones and offers the rest as suggestions.
	//
	// Optional, and **the host decides what unspecified means: not safe.** The two mistakes
	// are not symmetric — a suggestion that should have been safe costs a manual edit,
	// and a
	// fix that should have been a suggestion rewrites someone's code. A plain `bool`
	// cannot
	// represent "did not say", so every authoring crate would have to choose a value
	// to send
	// when its author omitted one, and one of them mapping that to `true` would silently
	// make fixes auto-applicable with nothing here to catch it. `option<bool>` keeps
	// the
	// cautious answer an invariant of the boundary rather than a convention each language
	// re-decides. This is what `lanekeep-js`'s `read_fix` already does with an absent
	// property.
	Safe cm.Option[bool] `json:"safe"`
}

// MatchEntry represents the record "lanekeep:host/types@0.1.0#match-entry".
//
// One capture of a query match: the name the query gave it, and the node it bound.
//
//	record match-entry {
//		name: string,
//		node: node,
//	}
type MatchEntry struct {
	_    cm.HostLayout `json:"-"`
	Name string        `json:"name"`
	Node Node          `json:"node"`
}

// Match represents the list "lanekeep:host/types@0.1.0#match".
//
// A query match's captures.
//
// A list rather than a record, because a query's capture names are declared by the
// rule
// and are not known to this interface in advance, and WIT records have statically
// named
// fields. A capture that did not participate is simply absent. There is no WIT analog
// of
// a JavaScript object holding an explicit `undefined` under a key, so the ambiguity
// that
// distinction could cause does not exist here.
//
//	type match = list<match-entry>
type Match cm.List[MatchEntry]

// EmittedFact represents the record "lanekeep:host/types@0.1.0#emitted-fact".
//
// A fact emitted during the per-file pass, for the reduce phase to consume.
//
//	record emitted-fact {
//		kind: string,
//		file: string,
//		data: string,
//	}
type EmittedFact struct {
	_    cm.HostLayout `json:"-"`
	Kind string        `json:"kind"`
	File string        `json:"file"`

	// The rest of the payload, as the rule's own language serialized it to JSON. Opaque
	// to
	// the host beyond `kind` — a fact's shape is caller-defined. The host parses it and
	// rejects what is not a JSON object: under QuickJS `JSON.stringify` guaranteed the
	// shape, and a component can hand over any bytes it likes.
	Data string `json:"data"`
}

// RuleExamples represents the record "lanekeep:host/types@0.1.0#rule-examples".
//
// A short code snippet on each side of the rule: `bad` triggers it, `good` does not.
//
//	record rule-examples {
//		bad: string,
//		good: string,
//	}
type RuleExamples struct {
	_    cm.HostLayout `json:"-"`
	Bad  string        `json:"bad"`
	Good string        `json:"good"`
}

// RuleCard represents the record "lanekeep:host/types@0.1.0#rule-card".
//
// The three strings `lanekeep explain`, the agent reporter and context injection
// all
// read. Mandatory, together — a card with a message and no remediation tells an agent
// what is wrong and not what to do instead, which is the half that matters.
//
//	record rule-card {
//		message: string,
//		remediation: string,
//		examples: rule-examples,
//	}
type RuleCard struct {
	_           cm.HostLayout `json:"-"`
	Message     string        `json:"message"`
	Remediation string        `json:"remediation"`
	Examples    RuleExamples  `json:"examples"`
}

// RuleGates represents the record "lanekeep:host/types@0.1.0#rule-gates".
//
// Evaluated in Rust before the file is read or parsed. Purely an optimization — narrowing
// what gets read and parsed, never what a rule that ran would have reported.
//
// Mirrors `lanekeep_core::Gates` field for field. `path-matches` admits only a path
// matching one of these; `path-not-matches` is checked first and wins over it, skipping
// a
// path matching any of these even if `path-matches` would have admitted it. `file-contains`
// is an **and** — every listed substring must be present, so a rule matching either
// of two
// tokens cannot express it here and omits the gate instead — and `file-not-contains`
// is an
// **or**: a file whose bytes contain any of these is skipped.
//
//	record rule-gates {
//		path-matches: list<string>,
//		path-not-matches: list<string>,
//		file-contains: list<string>,
//		file-not-contains: list<string>,
//	}
type RuleGates struct {
	_               cm.HostLayout   `json:"-"`
	PathMatches     cm.List[string] `json:"path-matches"`
	PathNotMatches  cm.List[string] `json:"path-not-matches"`
	FileContains    cm.List[string] `json:"file-contains"`
	FileNotContains cm.List[string] `json:"file-not-contains"`
}

// RuleMetadata represents the record "lanekeep:host/types@0.1.0#rule-metadata".
//
// What a component says it is, read once at prepare time.
//
// A plain record returned by a function rather than a resource: it is read once and
// never again, and there is no per-call state for a resource to hold.
//
// The field set is exactly what `lanekeep-config`'s `EXTRACT` already harvests from
// a
// TypeScript module, and deliberately nothing more — a second, wider description
// of a rule
// is drift this record must not accumulate.
//
//	record rule-metadata {
//		id: string,
//		languages: list<string>,
//		severity: string,
//		card: rule-card,
//		query: string,
//		gates: rule-gates,
//		timeout: option<u64>,
//	}
type RuleMetadata struct {
	_  cm.HostLayout `json:"-"`
	ID string        `json:"id"`

	// One or several. A rule does not run on a file whose language it does not name —
	// which
	// means an empty list is not "every language," it is **no file at all**, and silently:
	// a
	// component that forgot to say what it targets would simply never fire, with nothing
	// to
	// report the mistake. The host refuses an empty list at load, before any file is
	// checked.
	Languages cm.List[string] `json:"languages"`
	Severity  string          `json:"severity"`
	Card      RuleCard        `json:"card"`
	Query     string          `json:"query"`
	Gates     RuleGates       `json:"gates"`

	// Milliseconds. None means the default per-invocation budget.
	Timeout cm.Option[uint64] `json:"timeout"`
}

// BindingKind represents the enum "lanekeep:host/types@0.1.0#binding-kind".
//
// How a name was introduced, as resolved by the language's binding resolution.
//
// Exactly two cases collide with a WIT keyword and are `%`-escaped for that reason
// alone; the escape carries no meaning. The rest are written bare because they are
// not
// keywords, which is measurable rather than assumed: `wasm-tools component wit` prints
// this file back with `%` on `import` and `type` and on nothing else, and `const`,
// `let`,
// `var`, `function`, `class`, `loop`, `module`, `trait` and `match` all parse unescaped.
// Escaping a non-keyword is legal, so an over-escaped version of this enum would
// have
// worked and would have said something false about WIT.
//
//	enum binding-kind {
//		%import,
//		const,
//		let,
//		var,
//		param,
//		function,
//		class,
//		catch-param,
//		assignment,
//		loop,
//		context-manager,
//		comprehension,
//		%type,
//		receiver,
//		type-param,
//		module,
//		trait
//	}
type BindingKind uint8

const (
	BindingKindImport BindingKind = iota
	BindingKindConst
	BindingKindLet
	BindingKindVar
	BindingKindParam
	BindingKindFunction
	BindingKindClass
	BindingKindCatchParam
	BindingKindAssignment
	BindingKindLoop
	BindingKindContextManager
	BindingKindComprehension
	BindingKindType
	BindingKindReceiver
	BindingKindTypeParam
	BindingKindModule
	BindingKindTrait
)

var _BindingKindStrings = [17]string{
	"import",
	"const",
	"let",
	"var",
	"param",
	"function",
	"class",
	"catch-param",
	"assignment",
	"loop",
	"context-manager",
	"comprehension",
	"type",
	"receiver",
	"type-param",
	"module",
	"trait",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e BindingKind) String() string {
	return _BindingKindStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e BindingKind) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *BindingKind) UnmarshalText(text []byte) error {
	return _BindingKindUnmarshalCase(e, text)
}

var _BindingKindUnmarshalCase = cm.CaseUnmarshaler[BindingKind](_BindingKindStrings[:])

// ReadError represents the variant "lanekeep:host/types@0.1.0#read-error".
//
// Why a tracked read was refused. Each case carries the offending path.
//
//	variant read-error {
//		escapes-root(string),
//		absolute(string),
//		not-text(string),
//	}
type ReadError cm.Variant[uint8, string, string]

// ReadErrorEscapesRoot returns a [ReadError] of case "escapes-root".
//
// The path resolved outside the project root.
func ReadErrorEscapesRoot(data string) ReadError {
	return cm.New[ReadError](0, data)
}

// EscapesRoot returns a non-nil *[string] if [ReadError] represents the variant case "escapes-root".
func (self *ReadError) EscapesRoot() *string {
	return cm.Case[string](self, 0)
}

// ReadErrorAbsolute returns a [ReadError] of case "absolute".
//
// The path was absolute, which a rule may not use — reads are root-relative so that
// a
// result does not depend on where the project sits on disk.
func ReadErrorAbsolute(data string) ReadError {
	return cm.New[ReadError](1, data)
}

// Absolute returns a non-nil *[string] if [ReadError] represents the variant case "absolute".
func (self *ReadError) Absolute() *string {
	return cm.Case[string](self, 1)
}

// ReadErrorNotText returns a [ReadError] of case "not-text".
//
// The file exists but is not valid UTF-8.
func ReadErrorNotText(data string) ReadError {
	return cm.New[ReadError](2, data)
}

// NotText returns a non-nil *[string] if [ReadError] represents the variant case "not-text".
func (self *ReadError) NotText() *string {
	return cm.Case[string](self, 2)
}

var _ReadErrorStrings = [3]string{
	"escapes-root",
	"absolute",
	"not-text",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v ReadError) String() string {
	return _ReadErrorStrings[v.Tag()]
}

// FactError represents the variant "lanekeep:host/types@0.1.0#fact-error".
//
// Why a fact was refused.
//
//	variant fact-error {
//		empty-kind,
//		not-an-object,
//		invalid-json(string),
//	}
type FactError cm.Variant[uint8, string, string]

// FactErrorEmptyKind returns a [FactError] of case "empty-kind".
//
// `kind` was empty, so nothing could select the fact in the reduce phase.
func FactErrorEmptyKind() FactError {
	var data struct{}
	return cm.New[FactError](0, data)
}

// EmptyKind returns true if [FactError] represents the variant case "empty-kind".
func (self *FactError) EmptyKind() bool {
	return self.Tag() == 0
}

// FactErrorNotAnObject returns a [FactError] of case "not-an-object".
//
// `data` parsed as JSON but was not an object.
func FactErrorNotAnObject() FactError {
	var data struct{}
	return cm.New[FactError](1, data)
}

// NotAnObject returns true if [FactError] represents the variant case "not-an-object".
func (self *FactError) NotAnObject() bool {
	return self.Tag() == 1
}

// FactErrorInvalidJSON returns a [FactError] of case "invalid-json".
//
// `data` did not parse as JSON. Carries the parser's message.
func FactErrorInvalidJSON(data string) FactError {
	return cm.New[FactError](2, data)
}

// InvalidJSON returns a non-nil *[string] if [FactError] represents the variant case "invalid-json".
func (self *FactError) InvalidJSON() *string {
	return cm.Case[string](self, 2)
}

var _FactErrorStrings = [3]string{
	"empty-kind",
	"not-an-object",
	"invalid-json",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v FactError) String() string {
	return _FactErrorStrings[v.Tag()]
}

// StackFrame represents the record "lanekeep:host/types@0.1.0#stack-frame".
//
// One frame of a guest's own stack, innermost first.
//
// Positions are in whatever space the guest was compiled to — for a bundled JavaScript
// rule that is the bundle, not the author's TypeScript. The host remaps them through
// the
// component's source map before a user sees one.
//
//	record stack-frame {
//		function: string,
//		file: string,
//		line: u32,
//		column: u32,
//	}
type StackFrame struct {
	_        cm.HostLayout `json:"-"`
	Function string        `json:"function"`
	File     string        `json:"file"`
	Line     uint32        `json:"line"`
	Column   uint32        `json:"column"`
}

// RuleError represents the record "lanekeep:host/types@0.1.0#rule-error".
//
// Why a rule failed, when its language can say.
//
// A rule that fails *gracefully* returns one of these; a rule that traps still traps,
// and
// the host handles both. This exists because a guest with no error channel loses
// everything: measured 2026-08-10, an uncaught JavaScript throw inside a component
// reaches the host as `wasm trap: unreachable` with the message, the type and the
// stack
// all gone. A Rust guest that panics is that case and stays that case; `frames` is
// empty
// for a language with no stack to offer.
//
//	record rule-error {
//		message: string,
//		frames: list<stack-frame>,
//	}
type RuleError struct {
	_       cm.HostLayout       `json:"-"`
	Message string              `json:"message"`
	Frames  cm.List[StackFrame] `json:"frames"`
}

// CheckContext represents the imported resource "lanekeep:host/types@0.1.0#check-context".
//
// The per-file phase's capabilities, and the parse tree it is reading.
//
// Held as a resource rather than passed as a record so that its method set *is* the
// enforcement `docs/architecture.md` §6.5 asks for: a per-file rule is handed one
// of
// these and nothing else, and there is no exported constructor, so it cannot make
// one of
// the other kind.
//
//	resource check-context
type CheckContext cm.Resource

// ResourceDrop represents the imported resource-drop for resource "check-context".
//
// Drops a resource handle.
//
//go:nosplit
func (self CheckContext) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_CheckContextResourceDrop((uint32)(self0))
	return
}

// Ancestors represents the imported method "ancestors".
//
// Every ancestor, nearest first, ending at the root.
//
//	ancestors: func(n: node) -> list<node>
//
//go:nosplit
func (self CheckContext) Ancestors(n Node) (result cm.List[Node]) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	wasmimport_CheckContextAncestors((uint32)(self0), (uint32)(n0), &result)
	return
}

// BindingKind represents the imported method "binding-kind".
//
// How the binding the identifier at `n` resolves to was introduced.
//
//	binding-kind: func(n: node) -> option<binding-kind>
//
//go:nosplit
func (self CheckContext) BindingKind(n Node) (result cm.Option[BindingKind]) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	wasmimport_CheckContextBindingKind((uint32)(self0), (uint32)(n0), &result)
	return
}

// Children represents the imported method "children".
//
// Every child, named and anonymous, in tree order.
//
//	children: func(n: node) -> list<node>
//
//go:nosplit
func (self CheckContext) Children(n Node) (result cm.List[Node]) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	wasmimport_CheckContextChildren((uint32)(self0), (uint32)(n0), &result)
	return
}

// ClosestAncestor represents the imported method "closest-ancestor".
//
// The nearest ancestor of `n` matching the query, or none.
//
// `option<match>` rather than an empty list, deliberately: an empty object is truthy
// in JavaScript, so a "nothing matched" value shaped like a match takes the wrong
// branch under `if (!...)`. The error is the query compiler's message.
//
//	closest-ancestor: func(n: node, query: string) -> result<option<match>, string>
//
//go:nosplit
func (self CheckContext) ClosestAncestor(n Node, query string) (result cm.Result[OptionMatchShape, cm.Option[Match], string]) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	query0, query1 := cm.LowerString(query)
	wasmimport_CheckContextClosestAncestor((uint32)(self0), (uint32)(n0), (*uint8)(query0), (uint32)(query1), &result)
	return
}

// Column represents the imported method "column".
//
// The node's one-based start column, on the same footing as `line`.
//
//	column: func(n: node) -> option<u32>
//
//go:nosplit
func (self CheckContext) Column(n Node) (result cm.Option[uint32]) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	wasmimport_CheckContextColumn((uint32)(self0), (uint32)(n0), &result)
	return
}

// EmitFact represents the imported method "emit-fact".
//
// Emit a fact for the reduce phase. `data` must be a JSON object.
//
//	emit-fact: func(kind: string, data: string) -> result<_, fact-error>
//
//go:nosplit
func (self CheckContext) EmitFact(kind string, data string) (result cm.Result[FactError, struct{}, FactError]) {
	self0 := cm.Reinterpret[uint32](self)
	kind0, kind1 := cm.LowerString(kind)
	data0, data1 := cm.LowerString(data)
	wasmimport_CheckContextEmitFact((uint32)(self0), (*uint8)(kind0), (uint32)(kind1), (*uint8)(data0), (uint32)(data1), &result)
	return
}

// FileExists represents the imported method "file-exists".
//
// Whether another file exists, root-relative. Tracked exactly as `read-file` is.
//
//	file-exists: func(path: string) -> result<bool, read-error>
//
//go:nosplit
func (self CheckContext) FileExists(path string) (result cm.Result[ReadErrorShape, bool, ReadError]) {
	self0 := cm.Reinterpret[uint32](self)
	path0, path1 := cm.LowerString(path)
	wasmimport_CheckContextFileExists((uint32)(self0), (*uint8)(path0), (uint32)(path1), &result)
	return
}

// FilePath represents the imported method "file-path".
//
// The path of the file being checked, relative to the project root.
//
//	file-path: func() -> string
//
//go:nosplit
func (self CheckContext) FilePath() (result string) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_CheckContextFilePath((uint32)(self0), &result)
	return
}

// FileText represents the imported method "file-text".
//
// The full source text of the file being checked.
//
//	file-text: func() -> string
//
//go:nosplit
func (self CheckContext) FileText() (result string) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_CheckContextFileText((uint32)(self0), &result)
	return
}

// IsImportedFrom represents the imported method "is-imported-from".
//
// Whether the identifier at `n` resolves to a binding imported from a module matching
// the glob `pattern`.
//
//	is-imported-from: func(n: node, pattern: string) -> bool
//
//go:nosplit
func (self CheckContext) IsImportedFrom(n Node, pattern string) (result bool) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	pattern0, pattern1 := cm.LowerString(pattern)
	result0 := wasmimport_CheckContextIsImportedFrom((uint32)(self0), (uint32)(n0), (*uint8)(pattern0), (uint32)(pattern1))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// IsNamed represents the imported method "is-named".
//
// Whether the node is named in the grammar, as opposed to an anonymous token.
//
//	is-named: func(n: node) -> bool
//
//go:nosplit
func (self CheckContext) IsNamed(n Node) (result bool) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	result0 := wasmimport_CheckContextIsNamed((uint32)(self0), (uint32)(n0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// IsShadowed represents the imported method "is-shadowed".
//
// Whether the binding the identifier at `n` resolves to shadows an outer one.
//
//	is-shadowed: func(n: node) -> bool
//
//go:nosplit
func (self CheckContext) IsShadowed(n Node) (result bool) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	result0 := wasmimport_CheckContextIsShadowed((uint32)(self0), (uint32)(n0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// Kind represents the imported method "kind".
//
// The node's grammar kind, or none if the handle is not live in this context.
//
//	kind: func(n: node) -> option<string>
//
//go:nosplit
func (self CheckContext) Kind(n Node) (result cm.Option[string]) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	wasmimport_CheckContextKind((uint32)(self0), (uint32)(n0), &result)
	return
}

// Line represents the imported method "line".
//
// The node's one-based start line.
//
// One-based, matching every other position lanekeep reports: `node-location` below,
// the violations the engine sorts by `(ruleId, file, line, column)`, and the column
// `lanekeep-query` builds by adding one to tree-sitter's own zero-based figure. Both
// engines read the same `NodeArena::position`, so there is one answer rather than
// a
// convention per boundary — a zero-based reading here would put every component rule's
// violations one line and one column off what the identical TypeScript rule reports,
// which looks like a rule bug and is not one.
//
//	line: func(n: node) -> option<u32>
//
//go:nosplit
func (self CheckContext) Line(n Node) (result cm.Option[uint32]) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	wasmimport_CheckContextLine((uint32)(self0), (uint32)(n0), &result)
	return
}

// Loc represents the imported method "loc".
//
// The node's position, for a rule that needs to reason about it rather than report
// at
// it.
//
//	loc: func(n: node) -> option<node-location>
//
//go:nosplit
func (self CheckContext) Loc(n Node) (result cm.Option[NodeLocation]) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	wasmimport_CheckContextLoc((uint32)(self0), (uint32)(n0), &result)
	return
}

// NamedChildren represents the imported method "named-children".
//
// The named children only, in tree order.
//
//	named-children: func(n: node) -> list<node>
//
//go:nosplit
func (self CheckContext) NamedChildren(n Node) (result cm.List[Node]) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	wasmimport_CheckContextNamedChildren((uint32)(self0), (uint32)(n0), &result)
	return
}

// Parent represents the imported method "parent".
//
// The node's parent, or none at the root.
//
//	parent: func(n: node) -> option<node>
//
//go:nosplit
func (self CheckContext) Parent(n Node) (result cm.Option[Node]) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	wasmimport_CheckContextParent((uint32)(self0), (uint32)(n0), &result)
	return
}

// QuerySubtree represents the imported method "query-subtree".
//
// Run a query against the subtree rooted at `n`. The error is the query compiler's
// message.
//
//	query-subtree: func(n: node, query: string) -> result<list<match>, string>
//
//go:nosplit
func (self CheckContext) QuerySubtree(n Node, query string) (result cm.Result[cm.List[Match], cm.List[Match], string]) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	query0, query1 := cm.LowerString(query)
	wasmimport_CheckContextQuerySubtree((uint32)(self0), (uint32)(n0), (*uint8)(query0), (uint32)(query1), &result)
	return
}

// ReadFile represents the imported method "read-file".
//
// Read another file in the project, root-relative. The read is tracked: it becomes
// a
// dependency of this file's cached result. None means the file does not exist.
//
//	read-file: func(path: string) -> result<option<string>, read-error>
//
//go:nosplit
func (self CheckContext) ReadFile(path string) (result cm.Result[OptionStringShape, cm.Option[string], ReadError]) {
	self0 := cm.Reinterpret[uint32](self)
	path0, path1 := cm.LowerString(path)
	wasmimport_CheckContextReadFile((uint32)(self0), (*uint8)(path0), (uint32)(path1), &result)
	return
}

// Report represents the imported method "report".
//
// Report a violation at `n`.
//
// Two independently optional named parameters rather than one union argument: the
// union exists in the TypeScript API only because JavaScript has no optional named
// parameters, and WIT does.
//
//	report: func(n: node, message: option<string>, fix: option<fix>)
//
//go:nosplit
func (self CheckContext) Report(n Node, message cm.Option[string], fix cm.Option[Fix]) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	message0, message1, message2 := lower_OptionString(message)
	fix0, fix1, fix2, fix3, fix4, fix5 := lower_OptionFix(fix)
	wasmimport_CheckContextReport((uint32)(self0), (uint32)(n0), (uint32)(message0), (*uint8)(message1), (uint32)(message2), (uint32)(fix0), (uint32)(fix1), (*uint8)(fix2), (uint32)(fix3), (uint32)(fix4), (uint32)(fix5))
	return
}

// ResolvesToImport represents the imported method "resolves-to-import".
//
// Whether the identifier at `n` resolves to a binding introduced by importing `name`
// (or the module itself, when `name` is none) from `module`.
//
//	resolves-to-import: func(n: node, module: string, name: option<string>) -> bool
//
//go:nosplit
func (self CheckContext) ResolvesToImport(n Node, module string, name cm.Option[string]) (result bool) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	module0, module1 := cm.LowerString(module)
	name0, name1, name2 := lower_OptionString(name)
	result0 := wasmimport_CheckContextResolvesToImport((uint32)(self0), (uint32)(n0), (*uint8)(module0), (uint32)(module1), (uint32)(name0), (*uint8)(name1), (uint32)(name2))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// Root represents the imported method "root".
//
// The root node of the parsed file. Its handle is 0.
//
//	root: func() -> node
//
//go:nosplit
func (self CheckContext) Root() (result Node) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_CheckContextRoot((uint32)(self0))
	result = (Node)((uint32)(result0))
	return
}

// Text represents the imported method "text".
//
// The source text the node spans.
//
//	text: func(n: node) -> option<string>
//
//go:nosplit
func (self CheckContext) Text(n Node) (result cm.Option[string]) {
	self0 := cm.Reinterpret[uint32](self)
	n0 := (uint32)(n)
	wasmimport_CheckContextText((uint32)(self0), (uint32)(n0), &result)
	return
}

// Today represents the imported method "today".
//
// Today's date, as `YYYY-MM-DD`, or none when the rule is not permitted to observe
// it.
//
// A function, not a property. Every capability here is already a host-executed call,
// so "was the date read" is "did this implementation run" — the cache needs that
// answer, and there is no plain-data-property alternative it has to be distinguished
// from.
//
//	today: func() -> option<string>
//
//go:nosplit
func (self CheckContext) Today() (result cm.Option[string]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_CheckContextToday((uint32)(self0), &result)
	return
}

// ReduceContext represents the imported resource "lanekeep:host/types@0.1.0#reduce-context".
//
// The cross-file phase's capabilities.
//
// No node, no tree, no file text: the reduce phase consumes facts and the file list
// and
// nothing else, which is what keeps cross-file rules parallel and cacheable
// (`docs/architecture.md`'s reduce invariant). The absence is the point, and here
// it is
// structural — there is no method to decline.
//
//	resource reduce-context
type ReduceContext cm.Resource

// ResourceDrop represents the imported resource-drop for resource "reduce-context".
//
// Drops a resource handle.
//
//go:nosplit
func (self ReduceContext) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ReduceContextResourceDrop((uint32)(self0))
	return
}

// Facts represents the imported method "facts".
//
// The facts emitted during the per-file pass, optionally narrowed to one kind.
//
//	facts: func(kind: option<string>) -> list<emitted-fact>
//
//go:nosplit
func (self ReduceContext) Facts(kind cm.Option[string]) (result cm.List[EmittedFact]) {
	self0 := cm.Reinterpret[uint32](self)
	kind0, kind1, kind2 := lower_OptionString(kind)
	wasmimport_ReduceContextFacts((uint32)(self0), (uint32)(kind0), (*uint8)(kind1), (uint32)(kind2), &result)
	return
}

// Files represents the imported method "files".
//
// Every file the run considered, in the engine's deterministic order.
//
//	files: func() -> list<string>
//
//go:nosplit
func (self ReduceContext) Files() (result cm.List[string]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ReduceContextFiles((uint32)(self0), &result)
	return
}

// Report represents the imported method "report".
//
// Report a cross-file violation.
//
//	report: func(at: reduce-location, message: option<string>)
//
//go:nosplit
func (self ReduceContext) Report(at ReduceLocation, message cm.Option[string]) {
	self0 := cm.Reinterpret[uint32](self)
	at0, at1, at2, at3, at4, at5 := lower_ReduceLocation(at)
	message0, message1, message2 := lower_OptionString(message)
	wasmimport_ReduceContextReport((uint32)(self0), (*uint8)(at0), (uint32)(at1), (uint32)(at2), (uint32)(at3), (uint32)(at4), (uint32)(at5), (uint32)(message0), (*uint8)(message1), (uint32)(message2))
	return
}
