#!/usr/bin/env bash
# Regenerates the vendored TypeScript and TSX parsers: upstream's resolved grammar.json, patched
# by `patch.py`, generated by tree-sitter-cli. Run through `just typescript-grammar`.
#
# It proves its own toolchain before writing anything. The unpatched grammar.json is generated
# first and compared byte-for-byte with the parser.c upstream shipped; a CLI that does not
# reproduce upstream exactly would make every later diff of the patched output a mixture of the
# patch and the CLI, so it stops there. tree-sitter-cli 0.24.4 reproduces 0.23.2 exactly, both
# grammars, parser.c and node-types.json alike.
#
# Nothing in the crate is touched until both grammars have reproduced and regenerated, so a
# failure partway leaves the committed tree as it was rather than one new grammar beside an old
# one. Last, it writes `digests.txt`, which `src/lib.rs`'s
# `the_committed_grammar_is_the_last_regeneration` checks against the committed files — the
# two `parser.c` files are left out of diffs, so that test is where a hand edit shows.
#
# Not in any gate: it needs the network and a CLI the gate does not install.
set -euo pipefail
unset CDPATH

UPSTREAM_VERSION="0.23.2"
# The checksum `Cargo.lock` recorded for this version while lanekeep depended on it directly.
UPSTREAM_SHA256="6c5f76ed8d947a75cc446d5fccd8b602ebf0cde64ccf2ffa434d873d7a575eff"
CLI_VERSION="0.24.4"

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
crate="$(dirname "${here}")"

for tool in tree-sitter python3 curl tar cmp; do
  if ! command -v "${tool}" >/dev/null 2>&1; then
    echo "error: \`${tool}\` is required" >&2
    if [ "${tool}" = tree-sitter ]; then
      echo "  cargo install tree-sitter-cli --version ${CLI_VERSION} --locked" >&2
    fi
    exit 1
  fi
done

cli_version="$(tree-sitter --version)"
cli_version="${cli_version#tree-sitter }"
cli_version="${cli_version%% *}"
if [ "${cli_version}" != "${CLI_VERSION}" ]; then
  echo "error: tree-sitter ${CLI_VERSION} is required, found ${cli_version}" >&2
  echo "  cargo install tree-sitter-cli --version ${CLI_VERSION} --locked" >&2
  exit 1
fi

sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}

work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT

archive="${work}/upstream.crate"
curl -fsSL -o "${archive}" \
  "https://static.crates.io/crates/tree-sitter-typescript/tree-sitter-typescript-${UPSTREAM_VERSION}.crate"
actual="$(sha256 "${archive}")"
if [ "${actual}" != "${UPSTREAM_SHA256}" ]; then
  echo "error: tree-sitter-typescript ${UPSTREAM_VERSION} has sha256 ${actual}," >&2
  echo "  expected ${UPSTREAM_SHA256}" >&2
  exit 1
fi
tar -xzf "${archive}" -C "${work}"
upstream="${work}/tree-sitter-typescript-${UPSTREAM_VERSION}"

generate() {
  # generate <grammar.json> <directory>: the parser lands in <directory>/src.
  mkdir -p "$2"
  cp "$1" "$2/grammar.json"
  (cd "$2" && tree-sitter generate --abi 14 grammar.json)
}

for language in typescript tsx; do
  generate "${upstream}/${language}/src/grammar.json" "${work}/reproduce/${language}"
  for file in parser.c node-types.json; do
    if ! cmp -s "${work}/reproduce/${language}/src/${file}" "${upstream}/${language}/src/${file}"; then
      echo "error: tree-sitter ${cli_version} does not reproduce upstream's ${language}/src/${file}" >&2
      exit 1
    fi
  done

  python3 "${here}/patch.py" "${language}" \
    "${upstream}/${language}/src/grammar.json" "${work}/${language}.grammar.json"
  generate "${work}/${language}.grammar.json" "${work}/patched/${language}"

  staged="${work}/staged/${language}/src"
  mkdir -p "${staged}/tree_sitter"
  cp "${work}/${language}.grammar.json" "${staged}/grammar.json"
  cp "${work}/patched/${language}/src/parser.c" "${staged}/parser.c"
  cp "${work}/patched/${language}/src/node-types.json" "${staged}/node-types.json"
  cp "${work}/patched/${language}/src/tree_sitter/"*.h "${staged}/tree_sitter/"
  # The external scanner's entry points carry the grammar's name, so they follow the rename.
  sed "s/tree_sitter_${language}_external_scanner/tree_sitter_lanekeep_${language}_external_scanner/g" \
    "${upstream}/${language}/src/scanner.c" >"${staged}/scanner.c"
done

for language in typescript tsx; do
  rm -rf "${crate:?}/${language}/src"
  mkdir -p "${crate}/${language}"
  cp -R "${work}/staged/${language}/src" "${crate}/${language}/src"
done
mkdir -p "${crate}/common"
cp "${upstream}/common/scanner.h" "${crate}/common/scanner.h"

# Sorted with LC_ALL=C so the manifest does not depend on the locale it was written under.
manifest="${crate}/grammar/digests.txt"
{
  echo "# Written by grammar/regenerate.sh. Checked by src/lib.rs; do not edit by hand."
  (
    cd "${crate}"
    find common grammar/patch.py typescript/src tsx/src -type f | LC_ALL=C sort |
      while IFS= read -r file; do
        echo "$(sha256 "${file}")  ${file}"
      done
  )
} >"${manifest}"

echo "regenerated ${crate}/typescript and ${crate}/tsx from tree-sitter-typescript ${UPSTREAM_VERSION}"
