// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package rule represents the world "lanekeep:host/rule@0.1.0".
//
// What a rule component is today: seven exports over the host surface, for the one
// or more
// rules the component hosts.
//
// **A component hosts a *list* of rules, and every export but `rules` takes an index
// into
// it.** That was forced rather than chosen. One embedded JavaScript engine is 12.34
// MiB
// measured, and the rules on top of it are noise — three additional rules with real
// bodies
// cost 9,702 bytes — so one component per rule would ship four migrated built-ins
// as 49.37
// MiB where one shared component is 12.34 MiB. The shape also buys something for
// the target
// that did not need it: one Rust crate can ship a family of related rules in one
// 26 KB
// artifact. A rule authored alone is a ruleset of one, and pays a `u32` for it.
//
// **This list is still provisional, and the version number is where that shows.**
// `metadata` carries what a TypeScript rule's default export carries today (id, languages,
// severity, card, gates, query, timeout), read once at prepare time. `configure`
// is what a
// sub-project binding against this world needed and this file did not yet have: a
// call made
// once after instantiation, since a component cannot close over a host-supplied value
// the
// way a factory rule does in JavaScript, so a rule's options cross as JSON data instead
// —
// see `configure`'s own doc comment below for why that is a permanent expressiveness
// loss
// against a factory rather than a gap to design around.
//
// **Adding an export bumps `host_api_hash`, which is a cache-key input**, so every
// cached
// result in every checkout is invalidated by it — which is the right behavior, since
// a
// result computed against a world without the addition is not a valid result for
// a run that
// has it. `metadata` paid that cost once, `configure` paid it again, and this change
// pays it
// a third time while also changing five signatures.
//
// **The rules of one component share an instance, and therefore share every global
// the guest
// keeps.** The host instantiates once per (worker, component) rather than once per
// rule —
// resident bytes are not artifact bytes: an instance grants 9,502,720 bytes before
// it runs,
// and one store takes seven of them and refuses the eighth with `MemoryExceeded`,
// so four is
// not a breach — what it costs is headroom, taking what is left for a rule's own
// allocations
// from 54.9 MiB to 27.8 MiB. So a `static mut`, a lazily
// built table, a memo: all of them are visible to every rule this component hosts,
// and *when*
// each rule sees them depends on the order the host's work-stealing scheduler handed
// a worker
// its files. `configure` is the only per-index state the arrangement guarantees.
//
// The rule that keeps this sound: **state outliving a `check` call must be derivable
// from
// that call's inputs.** A memo keyed on the file path is fine, because being handed
// a
// populated one is indistinguishable from being handed an empty one. A counter of
// files seen
// is not, and neither is anything `reduce` reads that `check` wrote to a variable
// rather than
// emitting as a fact — facts are the hand-off between the two phases and are per
// file by
// construction. A rule breaking this reports different violations depending on scheduling,
// which is the nondeterminism the whole design exists to make impossible.
package rule

import (
	"github.com/fmsouza/lanekeep/go-rules/internal/lanekeep/host/types"
)

// Node represents the type alias "lanekeep:host/rule@0.1.0#node".
//
// See [types.Node] for more information.
type Node = types.Node

// CheckContext represents the imported type alias "lanekeep:host/rule@0.1.0#check-context".
//
// See [types.CheckContext] for more information.
type CheckContext = types.CheckContext

// ReduceContext represents the imported type alias "lanekeep:host/rule@0.1.0#reduce-context".
//
// See [types.ReduceContext] for more information.
type ReduceContext = types.ReduceContext

// Match represents the type alias "lanekeep:host/rule@0.1.0#match".
//
// See [types.Match] for more information.
type Match = types.Match

// RuleMetadata represents the type alias "lanekeep:host/rule@0.1.0#rule-metadata".
//
// See [types.RuleMetadata] for more information.
type RuleMetadata = types.RuleMetadata

// RuleError represents the type alias "lanekeep:host/rule@0.1.0#rule-error".
//
// See [types.RuleError] for more information.
type RuleError = types.RuleError
