// Code generated by wit-bindgen-go. DO NOT EDIT.

package rule

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "lanekeep:host/rule@0.1.0".
var Exports struct {
	// Rules represents the caller-defined, exported function "rules".
	//
	// Every rule this component hosts, by id, in index order. The index is the `rule`
	// parameter every other export takes.
	//
	// Ids rather than full metadata, and the split is load-bearing. `configure` must
	// run
	// before metadata is read, because a factory rule's card and query are produced by
	// applying the factory to its options. But to configure rule *i* you must know *i*
	// exists. A rule's id cannot depend on its options — the id is how a config names
	// the
	// rule — so ids enumerate before configuration and everything else is read after
	// it.
	//
	//	rules: func() -> list<string>
	Rules func() (result cm.List[string])

	// Metadata represents the caller-defined, exported function "metadata".
	//
	// What one of this component's rules is. Read once, at prepare time, before any file
	// is
	// checked, and after that rule has been configured.
	//
	//	metadata: func(rule: u32) -> rule-metadata
	Metadata func(rule uint32) (result RuleMetadata)

	// Configure represents the caller-defined, exported function "configure".
	//
	// Hand one of this component's rules its configured options, once, after instantiation
	// and before any `check`.
	//
	// JSON rather than a typed record, because a rule's options are its own design and
	// this
	// interface cannot know their shape. A component has no way to close over a host-supplied
	// value the way a JavaScript factory does, so the value crosses as data — which is
	// a
	// permanent expressiveness loss against a factory, named rather than designed around:
	// no
	// functions, no regular expressions, nothing a `Deserialize` cannot represent.
	//
	// `null` when a rule was named with no options, so a guest has one code path rather
	// than
	// two. The error is the guest's own message, and it fails the run rather than trapping
	// —
	// a rule that cannot use its configuration has not merely misbehaved, it has been
	// misconfigured, and the user needs to be told which.
	//
	//	configure: func(rule: u32, options-json: string) -> result<_, string>
	Configure func(rule uint32, optionsJSON string) (result cm.Result[string, struct{}, string])

	// HasCheck represents the caller-defined, exported function "has-check".
	//
	// Whether this rule has a per-file pass.
	//
	// **Probed once per rule at config load, and the answer is what the engine dispatches
	// on.**
	// `lanekeep-config` calls this and `has-reduce` immediately after `metadata`, and
	// folds all
	// three into the rule's spec — so a component describes its own passes and is no
	// longer
	// taken at its config's word. This mirrors how the presence of `check` is discovered
	// for a
	// TypeScript rule, by inspecting the evaluated module rather than by trusting hand-written
	// config.
	//
	// A component that answers `false` here fails config load outright, with the same
	// message a
	// TypeScript rule missing its handler gets: a rule that can never report is a misconfigured
	// rule, not a quiet no-op.
	//
	//	has-check: func(rule: u32) -> bool
	HasCheck func(rule uint32) (result bool)

	// HasReduce represents the caller-defined, exported function "has-reduce".
	//
	// Whether this rule has a cross-file pass, on the same terms.
	//
	// Every component exports all seven functions regardless of which passes its rules
	// use,
	// because a WIT world has no optional exports. A check-only rule's `reduce` is a
	// no-op its
	// own language's scaffolding supplies.
	//
	//	has-reduce: func(rule: u32) -> bool
	HasReduce func(rule uint32) (result bool)

	// Check represents the caller-defined, exported function "check".
	//
	// Run one rule's per-file pass for one query match.
	//
	// `borrow<check-context>`: the host owns the context and lends it for the call, so
	// the
	// handle is dead the moment `check` returns and cannot be stashed for a later one.
	//
	// The `result` is the graceful-failure channel, and it is not a second way of spelling
	// a
	// trap. A guest that traps loses everything it knew — measured 2026-08-10, an uncaught
	// JavaScript throw arrives as `wasm trap: unreachable` with no message, no type and
	// no
	// stack — so a rule that can catch its own failure has to be able to hand one back,
	// or the
	// host has nothing to remap through the component's source map and nothing to name
	// in a
	// diagnostic. A Rust guest that panics still traps, and the host still handles it;
	// this
	// adds a way to fail gracefully and removes nothing.
	//
	//	check: func(rule: u32, ctx: borrow<check-context>, m: match) -> result<_, rule-error>
	Check func(rule uint32, ctx cm.Rep, m Match) (result cm.Result[RuleError, struct{}, RuleError])

	// Reduce represents the caller-defined, exported function "reduce".
	//
	// Run one rule's cross-file pass, once per run, on the same terms as `check`.
	//
	//	reduce: func(rule: u32, ctx: borrow<reduce-context>) -> result<_, rule-error>
	Reduce func(rule uint32, ctx cm.Rep) (result cm.Result[RuleError, struct{}, RuleError])
}
