// Code generated by wit-bindgen-go. DO NOT EDIT.

package rule

import (
	"github.com/fmsouza/lanekeep/go-rules/internal/lanekeep/host/types"
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "lanekeep:host@0.1.0".

//go:wasmexport rules
//export rules
func wasmexport_Rules() (result *cm.List[string]) {
	result_ := Exports.Rules()
	result = &result_
	return
}

//go:wasmexport metadata
//export metadata
func wasmexport_Metadata(rule0 uint32) (result *RuleMetadata) {
	rule := (uint32)((uint32)(rule0))
	result_ := Exports.Metadata(rule)
	result = &result_
	return
}

//go:wasmexport configure
//export configure
func wasmexport_Configure(rule0 uint32, optionsJson0 *uint8, optionsJson1 uint32) (result *cm.Result[string, struct{}, string]) {
	rule := (uint32)((uint32)(rule0))
	optionsJSON := cm.LiftString[string]((*uint8)(optionsJson0), (uint32)(optionsJson1))
	result_ := Exports.Configure(rule, optionsJSON)
	result = &result_
	return
}

//go:wasmexport has-check
//export has-check
func wasmexport_HasCheck(rule0 uint32) (result0 uint32) {
	rule := (uint32)((uint32)(rule0))
	result := Exports.HasCheck(rule)
	result0 = (uint32)(cm.BoolToU32(result))
	return
}

//go:wasmexport has-reduce
//export has-reduce
func wasmexport_HasReduce(rule0 uint32) (result0 uint32) {
	rule := (uint32)((uint32)(rule0))
	result := Exports.HasReduce(rule)
	result0 = (uint32)(cm.BoolToU32(result))
	return
}

//go:wasmexport check
//export check
func wasmexport_Check(rule0 uint32, ctx0 uint32, m0 *types.MatchEntry, m1 uint32) (result *cm.Result[RuleError, struct{}, RuleError]) {
	rule := (uint32)((uint32)(rule0))
	ctx := cm.Reinterpret[cm.Rep]((uint32)(ctx0))
	m := cm.LiftList[types.Match]((*types.MatchEntry)(m0), (uint32)(m1))
	result_ := Exports.Check(rule, ctx, m)
	result = &result_
	return
}

//go:wasmexport reduce
//export reduce
func wasmexport_Reduce(rule0 uint32, ctx0 uint32) (result *cm.Result[RuleError, struct{}, RuleError]) {
	rule := (uint32)((uint32)(rule0))
	ctx := cm.Reinterpret[cm.Rep]((uint32)(ctx0))
	result_ := Exports.Reduce(rule, ctx)
	result = &result_
	return
}
