//! `local/binding-kinds-are-typed`: a binding kind a resolver can return that the `BindingKind`
//! union does not include.
//!
//! `ctx.bindingKind` is typed as a union rather than as `string`, which is only useful while
//! the union is complete. A language crate adding a kind without adding it here narrows an
//! author's `switch` to something wrong — silently, since the missing arm just never matches.
//!
//! The kinds are read from `as_str` and `kind_str`'s match arms rather than from a list, for
//! the same reason the host surface is read from `host.rs`: the compiler already forces each
//! match to be exhaustive, so together they are the one place that cannot fall behind the enum.
//! Three languages have each added kinds beyond the original JavaScript/TypeScript set —
//! `assignment`, `loop`, `context-manager` and `comprehension` for Python, `type`, `receiver`
//! and `type-param` for Go, `module` and `trait` for Rust — on the test that the nearest
//! existing kind would have been untrue.
//!
//! `packages/lanekeep/index.d.ts` is read through `ctx.read_file`, so it is recorded as a cache
//! dependency and editing either file invalidates this entry.
//!
//! # A port, held to reporting identically
//!
//! This is `lanekeep/rules/binding-kinds-are-typed.ts`, which was a TypeScript module until it
//! was this. The original was deleted in the commit that made this the shipped rule;
//! `git log --diff-filter=D -- lanekeep/rules/binding-kinds-are-typed.ts` finds it. The two ran
//! against one shared table of cases in `crates/lanekeep-rules/tests/binding_kinds_are_typed.rs`
//! until then, and the claim that table exists to hold is that they report the same violations
//! at the same positions with the same messages.
//!
//! **That claim outlives the file it was written against.** A difference here is a bug even when
//! it reads like an improvement, because the users being kept faith with are the ones whose
//! configs did not change: `Options` below does not reject an unknown key, for instance, because
//! the TypeScript rule ignored one and a stricter component would fail a run that used to pass.
//!
//! There are no unit tests in this crate, and that is a decision rather than an omission. It does
//! not compile at all without the `src/bindings.rs` that `cargo component build` generates, which
//! neither gate runs — so a `#[cfg(test)]` module here would be a test nobody executes, and one
//! of those is worse than none. Everything worth asserting is a case in that shared table
//! instead, where both implementations are held to it at once.
//!
//! # Nothing here may panic
//!
//! A panic in a guest is a trap, and a trap aborts the call before any report crosses back — so
//! a wrong assumption about a node's shape surfaces as "the host recorded no violations", which
//! is exactly what a broken `report` looks like too. Every lookup below is a `find` or a `get`
//! with an explicit fallback, and there is no indexing and no slicing anywhere in this file.

// The generated bindings. `warnings` covers the workspace's warn-level lints; `unsafe_code` is
// denied there and is not in the `warnings` group, and `wit-bindgen`'s output is unavoidably
// unsafe — it implements the canonical ABI. Scoped to this declaration and to the `export!`
// expansion at the bottom of the file rather than made a crate-level allow, so the rule's own
// code is still held to the workspace's `deny`.
#[allow(
    warnings,
    unsafe_code,
    reason = "`src/bindings.rs` is generated by `cargo component build` and implements the \
              canonical ABI, which cannot be written in safe Rust."
)]
mod bindings;

use std::cell::RefCell;
use std::collections::HashSet;

use bindings::lanekeep::host::types::{
    MatchEntry, RuleCard, RuleError, RuleExamples, RuleGates, RuleMetadata,
};
use bindings::{CheckContext, Guest, Match, ReduceContext};
// `Node` comes from the SDK rather than from the bindings, and there is nothing to reconcile:
// `wit-bindgen` resolves the world's `type node = u32` to a bare `u32` and emits no alias for
// it, so the SDK's own `pub type Node = u32` is the same type under a name the signatures below
// can be read against.
use lanekeep_rule::{Capture, Node, capture};
use serde::Deserialize;

/// The capture bound to the whole file, which is where the missing-types finding is reported.
const ROOT: &str = "root";

/// The capture bound to the string literal on the right of a match arm.
const KIND: &str = "kind";

/// The capture bound to the whole match arm, which is where a missing kind is reported.
const ARM: &str = "arm";

/// The capture bound to the owning function's name.
const NAME: &str = "name";

/// The two functions that render a binding kind as the string `ctx.bindingKind` returns.
///
/// `as_str` covers every `BindingKind` variant. `kind_str` adds `import`, which is not a
/// `BindingKind` at all — `Binding::Import` is a separate arm of the enum above it — so scoping
/// to `as_str` alone would silently drop a real kind, and scoping to the whole file would pick
/// up any unrelated match with string arms.
const KIND_FUNCTIONS: [&str; 2] = ["as_str", "kind_str"];

thread_local! {
    /// The path of the binding file this run reconciles, as configured.
    ///
    /// A component has no way to close over its options the way a JavaScript factory closes over
    /// them, so they arrive through `configure` and have to be put somewhere the later `check`
    /// calls can read. One instance is configured once and then checks many matches, which is
    /// why this is interior mutability rather than a value threaded through a call — the world
    /// gives `check` no parameter to thread it through.
    ///
    /// `RefCell` cannot be re-entered here: `configure` only writes and `check` only reads, and
    /// neither borrow outlives the closure it is taken in.
    static BINDING_PATH: RefCell<String> = const { RefCell::new(String::new()) };
    /// The path of the types file, on the same terms as [`BINDING_PATH`].
    static TYPES_PATH: RefCell<String> = const { RefCell::new(String::new()) };
}

/// This rule's options, as `configure` receives them.
///
/// `Option<String>` rather than `#[serde(default)] String`, so that an explicit `null` is the
/// default rather than a refusal — the TypeScript original spells this `options?.bindingPath ?? …`,
/// which treats a null and a missing key alike, and a port that refused one of them would fail
/// a config the rule used to accept.
///
/// Unknown keys are accepted for the same reason. `deny_unknown_fields` would catch a typo,
/// which is a real benefit, and it is not taken here because the rule this replaces ignores one:
/// making the component stricter would turn a working config into a failed run at the moment the
/// rule is swapped over, which is not a change that belongs inside a migration.
#[derive(Debug, Default, Deserialize)]
struct Options {
    #[serde(rename = "bindingPath")]
    binding_path: Option<String>,
    #[serde(rename = "typesPath")]
    types_path: Option<String>,
}

/// A generated capture, seen through the SDK's projection.
///
/// One `impl` rather than a conversion at every `check`: `Capture` asserts a shape — "has a name
/// and a node" — over the type `wit-bindgen` generated in *this* crate, so there is no second
/// Rust copy of the WIT record to drift from it, and no orphan-rule problem either.
impl Capture for MatchEntry {
    fn name(&self) -> &str {
        &self.name
    }

    fn node(&self) -> Node {
        self.node
    }
}

struct BindingKindsAreTyped;

impl Rule for BindingKindsAreTyped {
    fn metadata() -> RuleMetadata {
        RuleMetadata {
            id: "local/binding-kinds-are-typed".to_owned(),
            languages: vec!["rust".to_owned()],
            severity: "error".to_owned(),
            card: RuleCard {
                message: "binding kind missing from the BindingKind union".to_owned(),
                remediation: "add the kind to `BindingKind` in packages/lanekeep/index.d.ts — \
                              an author's switch on a narrowed union silently never matches"
                    .to_owned(),
                examples: RuleExamples {
                    bad: "Self::Trait => \"trait\" with no 'trait' in the union".to_owned(),
                    good: "both, in the same change".to_owned(),
                },
            },
            // One match per file: the whole reconciliation is a single invocation, because a
            // comparison of two sets cannot be made one call at a time.
            query: "(source_file) @root".to_owned(),
            // No gates, deliberately. The rule already returns early on any file that is not
            // the binding file, and the types file is read through `ctx.read_file` — so a gate
            // would only duplicate the early return and could not narrow the read.
            gates: RuleGates {
                path_matches: Vec::new(),
                path_not_matches: Vec::new(),
                file_contains: Vec::new(),
                file_not_contains: Vec::new(),
            },
            timeout: None,
        }
    }

    fn configure(options_json: String) -> Result<(), String> {
        // `Option<Options>` rather than `Options`, because the world sends `null` for a rule
        // named with no options and serde will not deserialize a null into a struct. One code
        // path either way, which is what the world's `null` is for.
        let options: Option<Options> = serde_json::from_str(&options_json).map_err(|e| {
            format!("local/binding-kinds-are-typed could not read its options: {e}")
        })?;
        let options = options.unwrap_or_default();
        let binding_path = options
            .binding_path
            .unwrap_or_else(|| "crates/lanekeep-lang/src/binding.rs".to_owned());
        let types_path = options
            .types_path
            .unwrap_or_else(|| "packages/lanekeep/index.d.ts".to_owned());
        BINDING_PATH.with_borrow_mut(|configured| *configured = binding_path);
        TYPES_PATH.with_borrow_mut(|configured| *configured = types_path);
        Ok(())
    }

    fn has_check() -> bool {
        true
    }

    /// No cross-file pass. Every export is mandatory because a WIT world has no optional ones.
    fn has_reduce() -> bool {
        false
    }

    fn check(ctx: &CheckContext, m: Match) -> Result<(), RuleError> {
        let Some(root) = capture(&m, ROOT) else {
            // The query below binds `root` on every match, so this is unreachable — and it is a
            // `return` rather than an assertion because the alternative in a guest is a trap,
            // which the host cannot tell apart from a rule that found nothing.
            return Ok(());
        };

        let binding_path = BINDING_PATH.with_borrow(String::clone);
        let types_path = TYPES_PATH.with_borrow(String::clone);

        // Only the binding file is this rule's business; every other file is skipped before the
        // types file is read, so a run over a whole project reads it once.
        if ctx.file_path() != binding_path {
            return Ok(());
        }

        // A refusal throws in the TypeScript original and an absence returns `undefined`; the
        // WIT `read_file` keeps that distinction as `Err` versus `Ok(None)`. The `Err` arm
        // fails the run the way the throw did, and the `None` arm reports the missing-types
        // message the original reports.
        let types = match ctx.read_file(&types_path) {
            Ok(Some(text)) => text,
            Ok(None) => {
                ctx.report(
                    root,
                    Some(&format!(
                        "`{types_path}` is missing, so the binding kinds have no union to agree \
                         with"
                    )),
                    None,
                );
                return Ok(());
            }
            Err(e) => {
                return Err(RuleError {
                    message: format!("could not read `{types_path}`: {e}"),
                    frames: Vec::new(),
                });
            }
        };

        let union = union_members(&types);

        // The string on the right of a match arm inside `as_str` or `kind_str`. Reading the arm
        // rather than the enum variant, because those are what a resolver's answer travels
        // through.
        let query = "(match_arm value: (string_literal) @kind) @arm";
        // The query is a compile-time constant, so the compiler cannot reject it; an error here
        // is unreachable, and an empty list is the safe direction for a rule that would
        // otherwise trap.
        let matches = ctx.query_subtree(root, query).unwrap_or_default();

        for hit in matches {
            let (Some(arm), Some(kind)) = (capture(&hit, ARM), capture(&hit, KIND)) else {
                continue;
            };

            // Scoped, not whole-file. An unrelated `match` with string arms — a `Display` impl,
            // an error-message match — would otherwise be reported as a missing binding kind.
            let owner = ctx
                .closest_ancestor(arm, "(function_item name: (identifier) @name) @fn")
                .unwrap_or_default();
            let Some(owner) = owner else {
                continue;
            };
            let Some(name) = capture(&owner, NAME) else {
                continue;
            };
            let name = ctx.text(name).unwrap_or_default();
            if !KIND_FUNCTIONS.contains(&name.as_str()) {
                continue;
            }

            let kind = ctx.text(kind).unwrap_or_default();
            let kind = strip_quotes(&kind);
            if kind.is_empty() {
                continue;
            }
            if union.contains(kind) {
                continue;
            }

            ctx.report(
                arm,
                Some(&format!(
                    "`{kind}` is a binding kind the resolvers can return, and BindingKind does \
                     not include it — an author's switch silently never matches it"
                )),
                None,
            );
        }

        Ok(())
    }

    /// Nothing. This rule has no cross-file pass; see [`BindingKindsAreTyped::has_reduce`].
    fn reduce(_ctx: &ReduceContext) -> Result<(), RuleError> {
        Ok(())
    }
}

/// The string literals in the `BindingKind` union type, as a set.
///
/// A text scan rather than a query, for the reason the crate documentation gives: no single
/// query matches both Rust match arms and TypeScript union members. Ports the TypeScript
/// `unionMembers`, which finds `export type BindingKind`, reads until the blank line, and
/// collects every `'...'`-quoted string.
fn union_members(types: &str) -> HashSet<String> {
    let mut members = HashSet::new();

    let Some(start) = types.find("export type BindingKind") else {
        return members;
    };
    let body = &types[start..];
    let end = body.find("\n\n").unwrap_or(body.len());
    let declaration = &body[..end];

    // `'[^']+'`: every run of non-quote characters between two quotes. A `find` of the next
    // quote is the same match, and the `+` is why an empty `''` is skipped.
    let mut rest = declaration;
    while let Some(open) = rest.find('\'') {
        let after_open = &rest[open + 1..];
        let Some(close) = after_open.find('\'') else {
            break;
        };
        if close > 0 {
            members.insert(after_open[..close].to_owned());
        }
        rest = &after_open[close + 1..];
    }

    members
}

/// Strip a Rust string literal's quotes and raw-string prefix, porting the TypeScript
/// `.replace(/^r?#*"/, '').replace(/"#*$/, '')`.
///
/// A Rust string literal carries its quotes, and a raw string carries `r` and any number of
/// `#`. Stripping a leading `r` unconditionally would eat the first letter of a kind that
/// starts with one — so the `r` is only stripped when it is followed by `#*"`, which is exactly
/// what a raw-string prefix looks like.
fn strip_quotes(text: &str) -> &str {
    let mut rest = text;

    // Leading `r?#*"`: an optional `r`, then any `#`, then the opening `"`.
    if let Some(after_r) = rest.strip_prefix('r') {
        rest = after_r;
    }
    let leading_hashes = rest.bytes().take_while(|&b| b == b'#').count();
    rest = &rest[leading_hashes..];
    if let Some(after_quote) = rest.strip_prefix('"') {
        rest = after_quote;
    }

    // Trailing `"#*`: the closing `"`, then any `#` after it. The TypeScript regex `/"#*$/`
    // matches a `"` followed by `#*` at the end, so the last `"` is found and stripped along
    // with whatever `#`s follow it — not the `#`s that precede it. Only when everything after
    // the last `"` is `#`s, so a kind that merely ends in `#` is not eaten.
    if let Some(quote) = rest.rfind('"')
        && rest[quote + 1..].bytes().all(|b| b == b'#')
    {
        rest = &rest[..quote];
    }

    rest
}

// The rules this component hosts, and the dispatch the world's rule index drives.
//
// One rule, so this component is a ruleset of one and answers to index zero. The macro is what
// keeps that true without this file spelling a number: `rules` reports the list and every other
// export looks its index back up in the same list, so an id and a type cannot drift apart.
//
// A plain comment rather than `///`: a doc comment on a macro invocation documents nothing, and
// `unused_doc_comments` is an error under this workspace's lints.
lanekeep_rule::ruleset! {
    "local/binding-kinds-are-typed" => BindingKindsAreTyped,
}

/// The canonical-ABI shims that make the seven exports reachable from the host.
///
/// In a module of its own so the `unsafe_code` the expansion needs is allowed *here* and not
/// across the rule's own code, which the workspace still denies it in. The macro takes bare
/// identifiers rather than paths, which is why the two it names are imported rather than
/// spelled out.
///
/// `warnings` alongside `unsafe_code`, on the same terms as `mod bindings` above: the expansion
/// calls `bindings`' own underscore-prefixed shims, which is seven `clippy::used_underscore_items`
/// under this workspace's `pedantic`. The `engine-rule` fixture this crate is modeled on has no
/// `[lints]` table of its own, so the template never had to answer for the expansion's lints and
/// dropping `warnings` here looks harmless right up until `cargo clippy` runs.
#[allow(
    warnings,
    unsafe_code,
    reason = "The expansion implements the canonical ABI, which cannot be written in safe Rust, \
              and reaches into the generated bindings' internal shims to do it."
)]
mod export {
    use super::{Component, bindings};

    bindings::export!(Component with_types_in bindings);
}
