#!/usr/bin/env bash
# Generate the Homebrew formula from a release's archives.
#
# Run from the repository root, against what `build-release-archives.sh` produced:
#
#   ./scripts/build-homebrew-formula.sh 0.3.0 dist-archives [output-file]
#
# The checksums come from `SHA256SUMS` beside the archives rather than being recomputed:
# that file is what a user verifies a download against, so a formula built from anything else
# could disagree with it, and the disagreement would only surface as a failed install.
#
# # Platforms
#
# Whatever the release actually built, and nothing else. There is no prebuilt Intel macOS
# binary — see the comment in `release.yml` — so the formula does not claim one. Writing a URL
# for an archive that was never uploaded produces a 404 at install time, which reads to a user
# like Homebrew being broken rather than like a platform not being shipped.
set -euo pipefail

version="${1:?usage: build-homebrew-formula.sh <version> <archives-dir> [output-file]}"
archives="${2:?usage: build-homebrew-formula.sh <version> <archives-dir> [output-file]}"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${3:-${repo_root}/dist-homebrew/lanekeep.rb}"

sums="${archives}/SHA256SUMS"
if [ ! -f "${sums}" ]; then
  echo "error: no SHA256SUMS in ${archives}" >&2
  exit 1
fi

# The checksum for one archive, as recorded. Empty when the archive was not built.
checksum_for() {
  awk -v name="$1" '$2 == name { print $1 }' "${sums}" | head -1
}

base="https://github.com/fmsouza/lanekeep/releases/download/v${version}"

darwin_arm="$(checksum_for "lanekeep-${version}-aarch64-apple-darwin.tar.gz")"
linux_arm="$(checksum_for "lanekeep-${version}-aarch64-unknown-linux-gnu.tar.gz")"
linux_x86="$(checksum_for "lanekeep-${version}-x86_64-unknown-linux-gnu.tar.gz")"

for pair in "aarch64-apple-darwin:${darwin_arm}" "aarch64-unknown-linux-gnu:${linux_arm}" \
  "x86_64-unknown-linux-gnu:${linux_x86}"; do
  triple="${pair%%:*}"
  sum="${pair##*:}"
  if [ -z "${sum}" ]; then
    # Loud, not silent. A platform missing from the formula is a platform whose users get an
    # install error, and nothing else would say so until one of them reported it.
    echo "error: no checksum for ${triple} in ${sums}" >&2
    exit 1
  fi
done

mkdir -p "$(dirname "${out}")"
# The two sigils are what `brew style` asks for, and a tap that lints clean is one that does
# not nag anyone who runs `brew audit` against it.
cat >"${out}" <<FORMULA
# typed: strict
# frozen_string_literal: true

# Generated by scripts/build-homebrew-formula.sh — do not edit by hand.
#
# lanekeep does not ship a prebuilt Intel macOS binary. On that platform, install with
# \`cargo install lanekeep-cli\`, which builds from source.
class Lanekeep < Formula
  desc "Deterministic, AST-based architectural conformance checking"
  homepage "https://github.com/fmsouza/lanekeep"
  version "${version}"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "${base}/lanekeep-${version}-aarch64-apple-darwin.tar.gz"
      sha256 "${darwin_arm}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/lanekeep-${version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "${base}/lanekeep-${version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_x86}"
    end
  end

  def install
    bin.install "lanekeep"
  end

  test do
    assert_match "lanekeep #{version}", shell_output("#{bin}/lanekeep --version")
  end
end
FORMULA

echo "wrote ${out} for ${version}"
