//! `local/no-ambient-observation`: clock and environment reads outside the two legitimate sites.
//!
//! §8.1: everything is deterministic given `(bytes, path, ruleset, config, tracked reads)`.
//! Anything else a result depends on is an input the cache key does not have, so the entry is
//! served for a run that would have computed something different. AGENTS.md states it without
//! the exception: "If you add anything that observes the environment, you have broken the
//! cache. There is no 'it's only used for logging' exception; a cached result is a cached
//! result."
//!
//! Two sites legitimately read the clock, and `allow` names both so the distinction is
//! reviewable rather than assumed:
//!
//! - `suppression::today`, which a suppression's `expires:` has to be compared against. Fixed
//!   once per run, in UTC, so two files checked a millisecond apart cannot disagree.
//! - `RunClock::start` in `lanekeep-js`, which fixes the origin the global run budget is
//!   measured from. A timeout clock cannot change *what* gets cached: §6.8 cancels the whole
//!   run on a breach — exit `2`, no report, no entry for any file still in flight — so it can
//!   stop a result being produced but cannot produce a different one.
//!
//! Anything else reading the clock is an input the cache key does not have.
//!
//! # A port, and a meaning that shifted with it
//!
//! This is `lanekeep/rules/no-ambient-observation.ts`, which was a TypeScript module until it
//! was this. The original was deleted in the commit that made this the shipped rule;
//! `git log --diff-filter=D -- lanekeep/rules/no-ambient-observation.ts` finds it. The two ran
//! against one shared table of cases in `crates/lanekeep-rules/tests/no_ambient_observation.rs`
//! until then, and the claim that table exists to hold is that they report the same violations
//! at the same positions with the same messages.
//!
//! **That claim outlives the file it was written against.** A difference here is a bug even when
//! it reads like an improvement, because the users being kept faith with are the ones whose
//! configs did not change: `Options` below does not reject an unknown key, for instance, because
//! the TypeScript rule ignored one and a stricter component would fail a run that used to pass.
//!
//! The meaning shifted when the rule became a component. Under WASM no clock is imported unless
//! the host imports one, so the engine's own Rust source can no longer observe the environment
//! by accident — the rule's force is now "no environment observation in the host's imports."
//! The Rust rule still scans the engine's Rust source for clock and environment reads, with the
//! two legitimate sites above in the `allow` set, but the boundary it polices is the host's
//! import surface rather than the engine's runtime.
//!
//! There are no unit tests in this crate, and that is a decision rather than an omission. It
//! does not compile at all without the `src/bindings.rs` that `cargo component build` generates,
//! which neither gate runs — so a `#[cfg(test)]` module here would be a test nobody executes, and
//! one of those is worse than none. Everything worth asserting is a case in that shared table
//! instead, where both implementations are held to it at once.
//!
//! # Nothing here may panic
//!
//! A panic in a guest is a trap, and a trap aborts the call before any report crosses back — so
//! a wrong assumption about a node's shape surfaces as "the host recorded no violations", which
//! is exactly what a broken `report` looks like too. Every lookup below is a `find` or a `get`
//! with an explicit fallback, and there is no indexing and no slicing anywhere in this file.

// The generated bindings. `warnings` covers the workspace's warn-level lints; `unsafe_code` is
// denied there and is not in the `warnings` group, and `wit-bindgen`'s output is unavoidably
// unsafe — it implements the canonical ABI. Scoped to this declaration and to the `export!`
// expansion at the bottom of the file rather than made a crate-level allow, so the rule's own
// code is still held to the workspace's `deny`.
#[allow(
    warnings,
    unsafe_code,
    reason = "`src/bindings.rs` is generated by `cargo component build` and implements the \
              canonical ABI, which cannot be written in safe Rust."
)]
mod bindings;

use std::cell::RefCell;

use bindings::lanekeep::host::types::{
    MatchEntry, RuleCard, RuleError, RuleExamples, RuleGates, RuleMetadata,
};
use bindings::{CheckContext, Guest, Match, ReduceContext};
// `Node` comes from the SDK rather than from the bindings, and there is nothing to reconcile:
// `wit-bindgen` resolves the world's `type node = u32` to a bare `u32` and emits no alias for
// it, so the SDK's own `pub type Node = u32` is the same type under a name the signatures below
// can be read against.
use lanekeep_rule::{Capture, Node, capture};
use serde::Deserialize;

/// The capture bound to the callee, whose text is checked against the forbidden list.
const CALLEE: &str = "callee";

/// The capture bound to the whole call, which is where a violation is reported.
const CALL: &str = "call";

/// The reads this rule is about, each qualified because the match is `callee.endsWith(forbidden)`.
///
/// A bare `'random'` would also match `getrandom::getrandom`. Note the limit: the query matches
/// `(call_expression function: (scoped_identifier))`, so an imported `use rand::thread_rng;`
/// called as plain `thread_rng()` is an `identifier` and never reaches `check`. That is
/// acceptable here because randomness needs a dependency this workspace does not have, and
/// adding one is itself a visible, reviewable act — this rule is the second line, not the only one.
const FORBIDDEN: &[&str] = &[
    "SystemTime::now",
    "Instant::now",
    "env::var",
    "env::vars",
    "env::current_dir",
    "rand::thread_rng",
    "rand::random",
];

/// The refusal for a rule scoped to nothing, which would silently check nothing.
const EMPTY_SCOPE: &str = "local/no-ambient-observation needs a non-empty `scope`; with none it \
                           silently checks nothing";

thread_local! {
    /// The path prefixes this run is about, as configured.
    ///
    /// A component has no way to close over its options the way a JavaScript factory closes over
    /// them, so they arrive through `configure` and have to be put somewhere the later `check`
    /// calls can read. One instance is configured once and then checks many matches, which is
    /// why this is interior mutability rather than a value threaded through a call — the world
    /// gives `check` no parameter to thread it through.
    ///
    /// `RefCell` cannot be re-entered here: `configure` only writes and `check` only reads, and
    /// neither borrow outlives the closure it is taken in.
    static SCOPE: RefCell<Vec<String>> = const { RefCell::new(Vec::new()) };

    /// The paths this run exempts, as configured.
    static ALLOW: RefCell<Vec<String>> = const { RefCell::new(Vec::new()) };
}

/// This rule's options, as `configure` receives them.
///
/// `Option<Vec<String>>` rather than `#[serde(default)] Vec<String>`, so that an explicit
/// `"allow": null` is the empty list rather than a refusal — the TypeScript original spells this
/// `options?.allow ?? []`, which treats a null and a missing key alike, and a port that refused
/// one of them would fail a config the rule used to accept.
///
/// Unknown keys are accepted for the same reason. `deny_unknown_fields` would catch a typo,
/// which is a real benefit, and it is not taken here because the rule this replaces ignores one:
/// making the component stricter would turn a working config into a failed run at the moment the
/// rule is swapped over, which is not a change that belongs inside a migration.
#[derive(Debug, Default, Deserialize)]
struct Options {
    scope: Option<Vec<String>>,
    allow: Option<Vec<String>>,
}

/// A generated capture, seen through the SDK's projection.
///
/// One `impl` rather than a conversion at every `check`: `Capture` asserts a shape — "has a name
/// and a node" — over the type `wit-bindgen` generated in *this* crate, so there is no second
/// Rust copy of the WIT record to drift from it, and no orphan-rule problem either.
impl Capture for MatchEntry {
    fn name(&self) -> &str {
        &self.name
    }

    fn node(&self) -> Node {
        self.node
    }
}

struct NoAmbientObservation;

impl Rule for NoAmbientObservation {
    fn metadata() -> RuleMetadata {
        RuleMetadata {
            id: "local/no-ambient-observation".to_owned(),
            languages: vec!["rust".to_owned()],
            severity: "error".to_owned(),
            card: RuleCard {
                message: "the environment observed where the result is cached".to_owned(),
                remediation: "take the value as a parameter, fixed once per run by the caller, \
                              so the cache key can account for it"
                    .to_owned(),
                examples: RuleExamples {
                    bad: "let today = SystemTime::now();".to_owned(),
                    good: "fn check(today: Date) { /* the host fixes it once per run */ }"
                        .to_owned(),
                },
            },
            query: "(call_expression function: (scoped_identifier) @callee) @call".to_owned(),
            // No `file-contains` gate, deliberately.
            //
            // It would be an *and* over every forbidden substring, and a file containing only
            // one of them would be rejected — which is nearly all of them. The failure is silent:
            // the rule loads, runs on nothing, and reads as a codebase with no ambient reads in
            // it. The query is the real gate; this only costs a parse on files that would have
            // been rejected.
            gates: RuleGates {
                path_matches: Vec::new(),
                path_not_matches: Vec::new(),
                file_contains: Vec::new(),
                file_not_contains: Vec::new(),
            },
            timeout: None,
        }
    }

    fn configure(options_json: String) -> Result<(), String> {
        // `Option<Options>` rather than `Options`, because the world sends `null` for a rule
        // named with no options and serde will not deserialize a null into a struct. One code
        // path either way, which is what the world's `null` is for.
        let options: Option<Options> = serde_json::from_str(&options_json)
            .map_err(|e| format!("local/no-ambient-observation could not read its options: {e}"))?;
        let options = options.unwrap_or_default();

        // A rule scoped to nothing checks nothing and reports a clean run, which is the failure
        // this whole rule set exists to prevent. `allow` defaults to empty and that is safe — it
        // makes the rule check *more*. `scope` is the opposite polarity, so an empty one has to
        // be refused rather than defaulted. Loud at config load beats silent forever.
        let scope = options.scope.unwrap_or_default();
        if scope.is_empty() {
            return Err(EMPTY_SCOPE.to_owned());
        }
        SCOPE.with_borrow_mut(|configured| *configured = scope);

        let allow = options.allow.unwrap_or_default();
        ALLOW.with_borrow_mut(|configured| *configured = allow);
        Ok(())
    }

    fn has_check() -> bool {
        true
    }

    /// No cross-file pass. Every export is mandatory because a WIT world has no optional ones.
    fn has_reduce() -> bool {
        false
    }

    fn check(ctx: &CheckContext, m: Match) -> Result<(), RuleError> {
        let (Some(callee), Some(call)) = (capture(&m, CALLEE), capture(&m, CALL)) else {
            // The query below binds both on every match, so this is unreachable — and it is a
            // `return` rather than an assertion because the alternative in a guest is a trap,
            // which the host cannot tell apart from a rule that found nothing.
            return Ok(());
        };

        // The rule is about the engine crates, not the whole workspace. The TypeScript original
        // tests the file path with `startsWith`, so this is a prefix match over `scope`.
        let file_path = ctx.file_path();
        if !SCOPE.with_borrow(|scope| scope.iter().any(|prefix| file_path.starts_with(prefix))) {
            return Ok(());
        }

        // The two sites that legitimately read the clock. The TypeScript original tests the file
        // path with `includes`, so this is an exact match rather than the prefix or glob the
        // other rules' `allow` lists use.
        if ALLOW.with_borrow(|allow| allow.iter().any(|path| path == &file_path)) {
            return Ok(());
        }

        let callee = ctx.text(callee).unwrap_or_default();
        if !FORBIDDEN
            .iter()
            .any(|forbidden| callee.ends_with(forbidden))
        {
            return Ok(());
        }

        ctx.report(
            call,
            Some(&format!(
                "`{callee}` is an input the cache key does not have, so an entry computed with \
                 it can be served for a run that would compute something else"
            )),
            None,
        );
        Ok(())
    }

    /// Nothing. This rule has no cross-file pass; see [`NoAmbientObservation::has_reduce`].
    fn reduce(_ctx: &ReduceContext) -> Result<(), RuleError> {
        Ok(())
    }
}

// The rules this component hosts, and the dispatch the world's rule index drives.
//
// One rule, so this component is a ruleset of one and answers to index zero. The macro is what
// keeps that true without this file spelling a number: `rules` reports the list and every other
// export looks its index back up in the same list, so an id and a type cannot drift apart.
//
// A plain comment rather than `///`: a doc comment on a macro invocation documents nothing, and
// `unused_doc_comments` is an error under this workspace's lints.
lanekeep_rule::ruleset! {
    "local/no-ambient-observation" => NoAmbientObservation,
}

/// The canonical-ABI shims that make the seven exports reachable from the host.
///
/// In a module of its own so the `unsafe_code` the expansion needs is allowed *here* and not
/// across the rule's own code, which the workspace still denies it in. The macro takes bare
/// identifiers rather than paths, which is why the two it names are imported rather than
/// spelled out.
///
/// `warnings` alongside `unsafe_code`, on the same terms as `mod bindings` above: the expansion
/// calls `bindings`' own underscore-prefixed shims, which is seven `clippy::used_underscore_items`
/// under this workspace's `pedantic`. The `engine-rule` fixture this crate is modeled on has no
/// `[lints]` table of its own, so the template never had to answer for the expansion's lints and
/// dropping `warnings` here looks harmless right up until `cargo clippy` runs.
#[allow(
    warnings,
    unsafe_code,
    reason = "The expansion implements the canonical ABI, which cannot be written in safe Rust, \
              and reaches into the generated bindings' internal shims to do it."
)]
mod export {
    use super::{Component, bindings};

    bindings::export!(Component with_types_in bindings);
}
