[package]
name = "lanekeep-engine"
description = "Rule execution engine for lanekeep."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
lanekeep-config = { workspace = true }
lanekeep-core = { workspace = true }
lanekeep-js = { workspace = true }
lanekeep-lang = { workspace = true }
lanekeep-query = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }
tree-sitter = { workspace = true }

[dev-dependencies]
lanekeep-lang-js = { workspace = true }

[lints]
workspace = true
