//! `lanekeep/no-glob-import`: `use foo::*;` outside an allowed prelude pattern.
//!
//! A glob import makes it impossible to answer, by reading the file, where a name came from.
//! Every unqualified identifier becomes a candidate for every glob in scope, and the answer
//! moves when an upstream crate adds a public item — a name that resolved to yours last week
//! resolves to theirs today, with no change on your side.
//!
//! That is an architectural cost rather than a stylistic one: it makes the module's dependency
//! surface unreadable, and it is exactly the case that defeats tooling too. lanekeep's own
//! binding resolver reports nothing for a glob import, because the names it brings in cannot be
//! known without reading the other crate — so a rule asking "is this the imported `Result`?"
//! quietly stops being answerable in any file that has one.
//!
//! The prelude conventions are the exception worth allowing, and `allow` exists for them,
//! defaulting to `*prelude*` and replacing that default entirely when configured — see
//! `Options` below.
//!
//! # A port, held to reporting identically
//!
//! This is `lanekeep/no-glob-import`, which was a TypeScript module until it was this. The
//! original was `crates/lanekeep-rules/rules/no-glob-import.ts`, deleted in the commit that made
//! this the shipped rule; `git log --diff-filter=D -- <that path>` finds it. The two ran against
//! one shared table of cases in `crates/lanekeep-rules/tests/no_glob_import.rs` until then, and
//! the claim that table exists to hold is that they report the same violations at the same
//! positions with the same messages — a claim that outlives the file it was written against,
//! because the users being kept faith with are the ones whose configs did not change.
//!
//! **The one detail a direct translation loses easily.** tree-sitter-rust's `use_wildcard` is
//! `(path '::')? '*'`, so the captured text already ends in `::*` — `ctx.text(wildcard)` for
//! `use crate::models::*;` is `crate::models::*`, whole. Appending another `::*` when building
//! the message below would reproduce exactly the bug the TypeScript original carried for its
//! entire life, reporting `use crate::models::*::*`, until the precursor to this migration fixed
//! it. `the_message_names_the_glob_once` in the shared table is the only thing that would catch
//! the doubling coming back here.
//!
//! There are no unit tests in this crate, and that is a decision rather than an omission, on the
//! same terms `no-unwrap` records: it does not compile at all without the `src/bindings.rs` that
//! `cargo component build` generates, which neither gate runs — so a `#[cfg(test)]` module here
//! would be a test nobody executes. Everything worth asserting is a case in the shared table
//! instead, where both implementations are held to it at once.
//!
//! # Nothing here may panic
//!
//! A panic in a guest is a trap, and a trap aborts the call before any report crosses back — so
//! a wrong assumption about a node's shape surfaces as "the host recorded no violations", which
//! is exactly what a broken `report` looks like too. Every lookup below is a `find` or a `get`
//! with an explicit fallback, and there is no indexing and no slicing anywhere in this file.

// The generated bindings. `warnings` covers the workspace's warn-level lints; `unsafe_code` is
// denied there and is not in the `warnings` group, and `wit-bindgen`'s output is unavoidably
// unsafe — it implements the canonical ABI. Scoped to this declaration and to the `export!`
// expansion at the bottom of the file rather than made a crate-level allow, so the rule's own
// code is still held to the workspace's `deny`.
#[allow(
    warnings,
    unsafe_code,
    reason = "`src/bindings.rs` is generated by `cargo component build` and implements the \
              canonical ABI, which cannot be written in safe Rust."
)]
mod bindings;

use std::cell::RefCell;

use bindings::lanekeep::host::types::{
    MatchEntry, RuleCard, RuleError, RuleExamples, RuleGates, RuleMetadata,
};
use bindings::{CheckContext, Guest, Match, ReduceContext};
// `Node` comes from the SDK rather than from the bindings, and there is nothing to reconcile:
// `wit-bindgen` resolves the world's `type node = u32` to a bare `u32` and emits no alias for
// it, so the SDK's own `pub type Node = u32` is the same type under a name the signatures below
// can be read against.
use lanekeep_rule::{Capture, Node, capture, glob_matches};
use serde::Deserialize;

/// The capture bound to the wildcard path — `crate::models::*`, `::*` included.
const WILDCARD: &str = "wildcard";

/// The capture bound to the whole `use` declaration, which is where a violation is reported.
const USE: &str = "use";

/// Preludes are the one shape a glob is the intended spelling of, and a project that uses one
/// should not have to suppress this on every file. Replaced rather than extended by a configured
/// `allow`; see [`Options`] and [`NoGlobImport::configure`].
const DEFAULT_ALLOW: &str = "*prelude*";

thread_local! {
    /// The patterns this run exempts a glob's path against, as configured.
    ///
    /// A component has no way to close over its options the way a JavaScript factory closes over
    /// them, so they arrive through `configure` and have to be put somewhere the later `check`
    /// calls can read. One instance is configured once and then checks many matches, which is
    /// why this is interior mutability rather than a value threaded through a call — the world
    /// gives `check` no parameter to thread it through.
    ///
    /// Seeded with the default rather than empty: the world's own contract has `configure` called
    /// once for every rule before any `check`, but a value here that meant "nothing exempted"
    /// until that call would make the moment between instantiation and configuration behave
    /// unlike either state the rule ever documents.
    ///
    /// `RefCell` cannot be re-entered here: `configure` only writes and `check` only reads, and
    /// neither borrow outlives the closure it is taken in.
    static ALLOW: RefCell<Vec<String>> = RefCell::new(vec![DEFAULT_ALLOW.to_owned()]);
}

/// This rule's options, as `configure` receives them.
///
/// `Option<Vec<String>>` rather than `#[serde(default)] Vec<String>`, so that an explicit
/// `"allow": null` falls back to [`DEFAULT_ALLOW`] exactly as a missing key does — the
/// TypeScript original spells this `options?.allow ?? ['*prelude*']`, where `??` treats `null`
/// and `undefined` alike, and a port that only defaulted a missing key would refuse a config the
/// original rule accepts.
///
/// Unknown keys are accepted for the same reason `no-unwrap`'s `Options` gives: the rule this
/// replaces ignores one, and a stricter component would turn a working config into a failed run
/// at the moment the built-in is swapped over, which is not a change that belongs inside a
/// migration.
#[derive(Debug, Default, Deserialize)]
struct Options {
    allow: Option<Vec<String>>,
}

/// A generated capture, seen through the SDK's projection.
///
/// One `impl` rather than a conversion at every `check`: `Capture` asserts a shape — "has a name
/// and a node" — over the type `wit-bindgen` generated in *this* crate, so there is no second
/// Rust copy of the WIT record to drift from it, and no orphan-rule problem either.
impl Capture for MatchEntry {
    fn name(&self) -> &str {
        &self.name
    }

    fn node(&self) -> Node {
        self.node
    }
}

struct NoGlobImport;

impl Rule for NoGlobImport {
    fn metadata() -> RuleMetadata {
        RuleMetadata {
            id: "lanekeep/no-glob-import".to_owned(),
            languages: vec!["rust".to_owned()],
            severity: "error".to_owned(),
            card: RuleCard {
                message: "glob import".to_owned(),
                remediation: "name what you import, so a reader can tell where each name comes \
                              from"
                    .to_owned(),
                examples: RuleExamples {
                    bad: "use crate::models::*;".to_owned(),
                    good: "use crate::models::{User, Session};".to_owned(),
                },
            },
            query: "(use_declaration argument: (use_wildcard) @wildcard) @use".to_owned(),
            // Unlike `no-unwrap`, this gate is expressible with one substring: every subject a
            // glob import can appear in contains the literal `use`, so `file-contains` — an
            // *and* over every listed substring — is satisfied by a single-element list rather
            // than needing the two-token gate `no-unwrap` cannot write.
            gates: RuleGates {
                path_matches: Vec::new(),
                path_not_matches: Vec::new(),
                file_contains: vec!["use".to_owned()],
                file_not_contains: Vec::new(),
            },
            timeout: None,
        }
    }

    fn configure(options_json: String) -> Result<(), String> {
        // `Option<Options>` rather than `Options`, because the world sends `null` for a rule
        // named with no options and serde will not deserialize a null into a struct. One code
        // path either way, which is what the world's `null` is for.
        let options: Option<Options> = serde_json::from_str(&options_json)
            .map_err(|e| format!("lanekeep/no-glob-import could not read its options: {e}"))?;
        let allow = options
            .and_then(|options| options.allow)
            .unwrap_or_else(|| vec![DEFAULT_ALLOW.to_owned()]);
        ALLOW.with_borrow_mut(|configured| *configured = allow);
        Ok(())
    }

    fn has_check() -> bool {
        true
    }

    /// No cross-file pass. Every export is mandatory because a WIT world has no optional ones.
    fn has_reduce() -> bool {
        false
    }

    fn check(ctx: &CheckContext, m: Match) -> Result<(), RuleError> {
        let (Some(wildcard), Some(use_decl)) = (capture(&m, WILDCARD), capture(&m, USE)) else {
            // The query below binds both on every match, so this is unreachable — and it is a
            // `return` rather than an assertion because the alternative in a guest is a trap,
            // which the host cannot tell apart from a rule that found nothing.
            return Ok(());
        };

        // Already ends in `::*`; see the module doc for why appending another here would be
        // the doubling bug this rule shipped with for its whole life before this migration.
        let path = ctx.text(wildcard).unwrap_or_default();

        let exempt =
            ALLOW.with_borrow(|allow| allow.iter().any(|pattern| glob_matches(pattern, &path)));
        if exempt {
            return Ok(());
        }

        ctx.report(
            use_decl,
            Some(&format!(
                "`use {path}` hides where every name in this file comes from"
            )),
            None,
        );
        Ok(())
    }

    /// Nothing. This rule has no cross-file pass; see [`NoGlobImport::has_reduce`].
    fn reduce(_ctx: &ReduceContext) -> Result<(), RuleError> {
        Ok(())
    }
}

// The rules this component hosts, and the dispatch the world's rule index drives.
//
// One rule, so this component is a ruleset of one and answers to index zero. The macro is what
// keeps that true without this file spelling a number: `rules` reports the list and every other
// export looks its index back up in the same list, so an id and a type cannot drift apart.
//
// A plain comment rather than `///`: a doc comment on a macro invocation documents nothing, and
// `unused_doc_comments` is an error under this workspace's lints.
lanekeep_rule::ruleset! {
    "lanekeep/no-glob-import" => NoGlobImport,
}

/// The canonical-ABI shims that make the seven exports reachable from the host.
///
/// In a module of its own so the `unsafe_code` the expansion needs is allowed *here* and not
/// across the rule's own code, which the workspace still denies it in. The macro takes bare
/// identifiers rather than paths, which is why the two it names are imported rather than
/// spelled out.
///
/// `warnings` alongside `unsafe_code`, on the same terms as `mod bindings` above: the expansion
/// calls `bindings`' own underscore-prefixed shims, which is seven `clippy::used_underscore_items`
/// under this workspace's `pedantic`. The `engine-rule` fixture this crate is modeled on has no
/// `[lints]` table of its own, so the template never had to answer for the expansion's lints and
/// dropping `warnings` here looks harmless right up until `cargo clippy` runs.
#[allow(
    warnings,
    unsafe_code,
    reason = "The expansion implements the canonical ABI, which cannot be written in safe Rust, \
              and reaches into the generated bindings' internal shims to do it."
)]
mod export {
    use super::{Component, bindings};

    bindings::export!(Component with_types_in bindings);
}
