//! `lanekeep/no-unwrap`: `.unwrap()` and `.expect()` outside tests.
//!
//! A library that panics on a malformed input has failed at its job: the caller wanted an error
//! it could handle and got a process abort instead. In a binary it is a crash with a stack trace
//! pointing at the unwrap rather than at the thing that was actually wrong.
//!
//! This is an architectural rule because the alternative is a convention nobody can enforce by
//! reading a diff — `?` and a typed error are more work at the call site, and the shortcut is
//! always available.
//!
//! In a test, panicking *is* the failure mechanism, so `#[test]` functions and files under a
//! `tests/` directory are not reported. That mirrors what a Rust project already does with
//! clippy's `unwrap_used`, and skipping it here would mean either a lint nobody can turn on or a
//! suppression on every assertion.
//!
//! # A port, held to reporting identically
//!
//! This is `lanekeep/no-unwrap`, which was a TypeScript module until it was this. The original
//! was `crates/lanekeep-rules/rules/no-unwrap.ts`, deleted in the commit that made this the
//! shipped rule; `git log --diff-filter=D -- <that path>` finds it. The two ran against one
//! shared table of cases in `crates/lanekeep-rules/tests/no_unwrap.rs` until then, and the claim
//! that table exists to hold is that they report the same violations at the same positions with
//! the same messages.
//!
//! **That claim outlives the file it was written against.** A difference here is a bug even when
//! it reads like an improvement, because the users being kept faith with are the ones whose
//! configs did not change: `Options` below does not reject an unknown key, for instance, because
//! the TypeScript rule ignored one and a stricter component would fail a run that used to pass.
//!
//! There are no unit tests in this crate, and that is a decision rather than an omission. It does
//! not compile at all without the `src/bindings.rs` that `cargo component build` generates, which
//! neither gate runs — so a `#[cfg(test)]` module here would be a test nobody executes, and one
//! of those is worse than none. Everything worth asserting, down to the `\b` in `mentions_test`
//! below, is a case in that shared table instead, where both implementations are held to it at
//! once.
//!
//! # Nothing here may panic
//!
//! A panic in a guest is a trap, and a trap aborts the call before any report crosses back — so
//! a wrong assumption about a node's shape surfaces as "the host recorded no violations", which
//! is exactly what a broken `report` looks like too. Every lookup below is a `find` or a `get`
//! with an explicit fallback, and there is no indexing and no slicing anywhere in this file.

// The generated bindings. `warnings` covers the workspace's warn-level lints; `unsafe_code` is
// denied there and is not in the `warnings` group, and `wit-bindgen`'s output is unavoidably
// unsafe — it implements the canonical ABI. Scoped to this declaration and to the `export!`
// expansion at the bottom of the file rather than made a crate-level allow, so the rule's own
// code is still held to the workspace's `deny`.
#[allow(
    warnings,
    unsafe_code,
    reason = "`src/bindings.rs` is generated by `cargo component build` and implements the \
              canonical ABI, which cannot be written in safe Rust."
)]
mod bindings;

use std::cell::RefCell;

use bindings::lanekeep::host::types::{
    MatchEntry, QueryFor, RuleCard, RuleError, RuleExamples, RuleGates, RuleMetadata,
};
use bindings::{CheckContext, Guest, Match, ReduceContext};
// `Node` comes from the SDK rather than from the bindings, and there is nothing to reconcile:
// `wit-bindgen` resolves the world's `type node = u32` to a bare `u32` and emits no alias for
// it, so the SDK's own `pub type Node = u32` is the same type under a name the signatures below
// can be read against.
use lanekeep_rule::{Capture, Node, capture, glob_matches};
use serde::Deserialize;

/// The capture bound to the method name — `unwrap`, `expect`, or something this rule ignores.
const METHOD: &str = "method";

/// The capture bound to the whole call, which is where a violation is reported.
const CALL: &str = "call";

/// The two methods this rule is about.
const UNWRAP: &str = "unwrap";
const EXPECT: &str = "expect";

thread_local! {
    /// The paths this run exempts, as configured.
    ///
    /// A component has no way to close over its options the way a JavaScript factory closes over
    /// them, so they arrive through `configure` and have to be put somewhere the later `check`
    /// calls can read. One instance is configured once and then checks many matches, which is
    /// why this is interior mutability rather than a value threaded through a call — the world
    /// gives `check` no parameter to thread it through.
    ///
    /// `RefCell` cannot be re-entered here: `configure` only writes and `check` only reads, and
    /// neither borrow outlives the closure it is taken in.
    static ALLOW: RefCell<Vec<String>> = const { RefCell::new(Vec::new()) };
}

/// This rule's options, as `configure` receives them.
///
/// `Option<Vec<String>>` rather than `#[serde(default)] Vec<String>`, so that an explicit
/// `"allow": null` is the empty list rather than a refusal — the TypeScript original spells this
/// `options?.allow ?? []`, which treats a null and a missing key alike, and a port that refused
/// one of them would fail a config the rule used to accept.
///
/// Unknown keys are accepted for the same reason. `deny_unknown_fields` would catch a typo,
/// which is a real benefit, and it is not taken here because the rule this replaces ignores one:
/// making the component stricter would turn a working config into a failed run at the moment the
/// built-in is swapped over, which is not a change that belongs inside a migration.
#[derive(Debug, Default, Deserialize)]
struct Options {
    allow: Option<Vec<String>>,
}

/// A generated capture, seen through the SDK's projection.
///
/// One `impl` rather than a conversion at every `check`: `Capture` asserts a shape — "has a name
/// and a node" — over the type `wit-bindgen` generated in *this* crate, so there is no second
/// Rust copy of the WIT record to drift from it, and no orphan-rule problem either.
impl Capture for MatchEntry {
    fn name(&self) -> &str {
        &self.name
    }

    fn node(&self) -> Node {
        self.node
    }
}

struct NoUnwrap;

impl Rule for NoUnwrap {
    fn metadata() -> RuleMetadata {
        RuleMetadata {
            id: "lanekeep/no-unwrap".to_owned(),
            languages: vec!["rust".to_owned()],
            severity: "error".to_owned(),
            card: RuleCard {
                message: "unwrap or expect outside a test".to_owned(),
                remediation: "propagate with `?` and a typed error, so the caller decides what \
                              a failure means"
                    .to_owned(),
                examples: RuleExamples {
                    bad: "let config = load().unwrap();".to_owned(),
                    good: "let config = load()?;".to_owned(),
                },
            },
            queries: lanekeep_rule::queries!["rust" => "(call_expression\n  function: (field_expression\n    field: (field_identifier) @method)) @call"
                .to_owned()],
            // No `file-contains` gate, deliberately.
            //
            // It would be the obvious optimization and it is not expressible: `file-contains` is
            // an *and* — every listed substring must be present — so `["unwrap", "expect"]`
            // rejects any file containing only one of them, which is nearly all of them. The
            // failure is silent: the rule loads, runs on nothing, and reads as a codebase with no
            // unwraps in it.
            //
            // There is no single substring covering both, so the gate is omitted rather than
            // written wrong. The query is still the real gate; this only costs a parse on files
            // that would have been rejected.
            gates: RuleGates {
                path_matches: Vec::new(),
                path_not_matches: Vec::new(),
                file_contains: Vec::new(),
                file_not_contains: Vec::new(),
            },
            timeout: None,
        }
    }

    fn configure(options_json: String) -> Result<(), String> {
        // `Option<Options>` rather than `Options`, because the world sends `null` for a rule
        // named with no options and serde will not deserialize a null into a struct. One code
        // path either way, which is what the world's `null` is for.
        let options: Option<Options> = serde_json::from_str(&options_json)
            .map_err(|e| format!("lanekeep/no-unwrap could not read its options: {e}"))?;
        let allow = options.unwrap_or_default().allow.unwrap_or_default();
        ALLOW.with_borrow_mut(|configured| *configured = allow);
        Ok(())
    }

    fn has_check() -> bool {
        true
    }

    /// No cross-file pass. Every export is mandatory because a WIT world has no optional ones.
    fn has_reduce() -> bool {
        false
    }

    fn check(ctx: &CheckContext, m: Match) -> Result<(), RuleError> {
        let (Some(method), Some(call)) = (capture(&m, METHOD), capture(&m, CALL)) else {
            // The query below binds both on every match, so this is unreachable — and it is a
            // `return` rather than an assertion because the alternative in a guest is a trap,
            // which the host cannot tell apart from a rule that found nothing.
            return Ok(());
        };

        let method = ctx.text(method).unwrap_or_default();
        if method != UNWRAP && method != EXPECT {
            return Ok(());
        }

        let path = ctx.file_path();

        // An integration test directory, and the conventional unit-test module name. Panicking
        // is the failure mechanism there, which is the whole point of a test.
        if path.contains("/tests/") || path.starts_with("tests/") {
            return Ok(());
        }
        if in_test_code(ctx, call) {
            return Ok(());
        }

        if ALLOW.with_borrow(|allow| allow.iter().any(|pattern| glob_matches(pattern, &path))) {
            return Ok(());
        }

        ctx.report(
            call,
            Some(&format!(
                "`{method}()` aborts the process where the caller wanted an error it could handle"
            )),
            None,
        );
        Ok(())
    }

    /// Nothing. This rule has no cross-file pass; see [`NoUnwrap::has_reduce`].
    fn reduce(_ctx: &ReduceContext) -> Result<(), RuleError> {
        Ok(())
    }
}

/// Whether this node sits inside `#[test]` or `#[cfg(test)]`.
///
/// Walked upwards rather than matched in the query, because the attribute is a *sibling* of the
/// item it applies to rather than a child — a query anchored on the attribute could not also
/// capture the call inside the function it decorates.
fn in_test_code(ctx: &CheckContext, node: Node) -> bool {
    let chain = ctx.ancestors(node);

    for (index, &ancestor) in chain.iter().enumerate() {
        let kind = ctx.kind(ancestor).unwrap_or_default();
        if kind != "function_item" && kind != "mod_item" {
            continue;
        }

        // The next entry in the chain, rather than `ctx.parent(ancestor)`.
        //
        // In TypeScript that mattered because a node crosses as an integer handle and the root's
        // is `0`, so `if (!parent)` discarded the root and no top-level `#[test]` was ever found.
        // Rust's `parent` returns `Option<Node>` and `Some(0)` is a perfectly good root, so the
        // bug is not expressible here — but `unwrap_or(0)` would put it back, and reading the
        // chain sidesteps the question the way the original does.
        let Some(&parent) = chain.get(index + 1) else {
            continue;
        };

        // Held once rather than asked per sibling. `None` is not reachable for a live handle,
        // and treating it as "no position" is the safe direction: comparing two absent positions
        // as equal would make the first sibling look like the item.
        let (Some(line), Some(column)) = (ctx.line(ancestor), ctx.column(ancestor)) else {
            continue;
        };

        // Attributes are *preceding siblings*, so walk the parent's children and keep the run of
        // `attribute_item`s immediately before this item. Reading the item's own children finds
        // nothing — which is a rule that silently never exempts anything.
        let mut attached: Vec<String> = Vec::new();
        for sibling in ctx.named_children(parent) {
            if ctx.kind(sibling).as_deref() == Some("attribute_item") {
                attached.push(ctx.text(sibling).unwrap_or_default());
                continue;
            }
            if ctx.line(sibling) == Some(line) && ctx.column(sibling) == Some(column) {
                if attached.iter().any(|a| mentions_test(a)) {
                    return true;
                }
                break;
            }
            // Any other item ends the run: those attributes belonged to it, not to us.
            attached.clear();
        }
    }
    false
}

/// Whether an attribute's text contains `test` as a whole word.
///
/// The TypeScript original writes this as `/\btest\b/`, so this is that regular expression and
/// not a looser reading of it: `#[test]`, `#[cfg(test)]` and `#[tokio::test]` match, while
/// `#[testing]` and `#[my_test]` do not — JavaScript's `\w` is `[A-Za-z0-9_]`, so an underscore
/// is a word character on both sides and `my_test` has no boundary before its `test`.
///
/// Non-overlapping search is exact here rather than approximate: a second `test` starting inside
/// a first would have a word character immediately before it, so it could not have matched
/// anyway.
fn mentions_test(text: &str) -> bool {
    let bytes = text.as_bytes();
    text.match_indices("test").any(|(start, needle)| {
        let before = start.checked_sub(1).and_then(|index| bytes.get(index));
        let after = bytes.get(start + needle.len());
        before.is_none_or(|b| !is_word_byte(*b)) && after.is_none_or(|b| !is_word_byte(*b))
    })
}

/// Whether a byte is one JavaScript's `\w` matches. ASCII only, as `\w` is.
fn is_word_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || byte == b'_'
}

// The rules this component hosts, and the dispatch the world's rule index drives.
//
// One rule, so this component is a ruleset of one and answers to index zero. The macro is what
// keeps that true without this file spelling a number: `rules` reports the list and every other
// export looks its index back up in the same list, so an id and a type cannot drift apart.
//
// A plain comment rather than `///`: a doc comment on a macro invocation documents nothing, and
// `unused_doc_comments` is an error under this workspace's lints.
lanekeep_rule::ruleset! {
    "lanekeep/no-unwrap" => NoUnwrap,
}

/// The canonical-ABI shims that make the seven exports reachable from the host.
///
/// In a module of its own so the `unsafe_code` the expansion needs is allowed *here* and not
/// across the rule's own code, which the workspace still denies it in. The macro takes bare
/// identifiers rather than paths, which is why the two it names are imported rather than
/// spelled out.
///
/// `warnings` alongside `unsafe_code`, on the same terms as `mod bindings` above: the expansion
/// calls `bindings`' own underscore-prefixed shims, which is seven `clippy::used_underscore_items`
/// under this workspace's `pedantic`. The `engine-rule` fixture this crate is modeled on has no
/// `[lints]` table of its own, so the template never had to answer for the expansion's lints and
/// dropping `warnings` here looks harmless right up until `cargo clippy` runs.
#[allow(
    warnings,
    unsafe_code,
    reason = "The expansion implements the canonical ABI, which cannot be written in safe Rust, \
              and reaches into the generated bindings' internal shims to do it."
)]
mod export {
    use super::{Component, bindings};

    bindings::export!(Component with_types_in bindings);
}
